from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
import xml.etree.ElementTree as ET

from onec_ordinary_forms.cli import digest_xml, semantic_model_hash
from onec_ordinary_forms.semantic_digest import semantic_graph, semantic_graph_digest


def form_xml(*, left: str = "8", noise: bool = False) -> str:
    noise_attrs = (
        ' containerCreatedTicks="100" containerModifiedTicks="200" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:noNamespaceSchemaLocation="OrdinaryForm.xsd"'
        if noise
        else ""
    )
    marker_attrs = ' layoutTail="0 0 0 1" primaryDimensionMarker="1"' if noise else ""
    return f"""<Form{noise_attrs}>
      <Title><Item lang="en">Main</Item></Title>
      <Events>
        <Event name="OnOpen" handler="OnOpen"/>
      </Events>
      <Attributes>
        <Attribute name="Items" type="ValueTable"/>
      </Attributes>
      <Pages>
        <Page name="Main">
          <CommandBar name="Bar" id="1">
            <CommandSource object="Form" autogenerated="true"/>
            <Buttons>
              <Button name="Generated">
                <CommandName>Refresh</CommandName>
                <Action name="Refresh"/>
              </Button>
            </Buttons>
          </CommandBar>
          <InputField name="Input" id="2" uuid="11111111-1111-1111-1111-111111111111">
            <Title><Item lang="en">Input</Item></Title>
            <Position left="{left}" top="8" right="120" bottom="28"{marker_attrs}>
              <Bindings>
                <Binding coordinate="left" mode="1"/>
                <DimensionBinding dimension="height" section="primary" value="0"/>
              </Bindings>
            </Position>
            <Font name="Arial" size="9"/>
            <TextColor kind="style" name="Text"/>
            <Picture path="Items/Input/Picture.gif"/>
            <Events>
              <Event name="OnChange" handler="InputOnChange"/>
            </Events>
          </InputField>
          <Table name="Table" id="3">
            <Position left="8" top="40" right="280" bottom="160"/>
            <Columns>
              <Column name="Quantity" order="1">
                <EditorControl>InputField</EditorControl>
              </Column>
            </Columns>
          </Table>
        </Page>
      </Pages>
    </Form>"""


def test_semantic_graph_covers_core_form_objects() -> None:
    graph = semantic_graph(ET.fromstring(form_xml()))

    assert graph["summary"] == {
        "controls": 3,
        "positions": 2,
        "bindings": 1,
        "dimensionBindings": 1,
        "events": 2,
        "attributes": 1,
        "columns": 1,
        "pictures": 1,
        "fonts": 1,
        "colors": 1,
        "commandSources": 3,
    }
    assert [control["type"] for control in graph["controls"]] == ["CommandBar", "InputField", "Table"]
    assert graph["controls"][1]["position"] == {"bottom": "28", "left": "8", "right": "120", "top": "8"}
    assert graph["tableColumns"][0]["editorControl"] == "InputField"


def test_semantic_digest_ignores_container_and_codec_noise() -> None:
    clean = semantic_graph_digest(ET.fromstring(form_xml()))
    noisy = semantic_graph_digest(ET.fromstring(form_xml(noise=True)))

    assert noisy == clean


def test_semantic_digest_changes_on_object_model_change() -> None:
    original = semantic_graph_digest(ET.fromstring(form_xml()))
    moved = semantic_graph_digest(ET.fromstring(form_xml(left="12")))

    assert moved != original


def test_legacy_semantic_model_hash_uses_full_graph_digest() -> None:
    root = ET.fromstring(form_xml())

    assert semantic_model_hash(root) == semantic_graph_digest(root)


def test_digest_xml_writes_report(tmp_path: Path) -> None:
    xml = tmp_path / "Form.xml"
    out = tmp_path / "digest.json"
    xml.write_text(form_xml(), encoding="utf-8")

    digest_xml(SimpleNamespace(xml=str(xml), out_json=str(out)))

    report = json.loads(out.read_text(encoding="utf-8"))
    assert report["summary"]["controls"] == 3
    assert len(report["hash"]) == 64
