<?xml version='1.0' encoding='utf-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation>Ordinary Form.xml public object model. The shape follows managed form XML: Form root, Events, ChildItems, Attributes, Commands, named controls, and nested ChildItems. Platform list-stream/bracket internals are implementation details and must not be exposed in this XML.</xs:documentation>
    <xs:appinfo>
      <PublicContract version="2.0" styleReference="http://v8.1c.ru/8.3/xcf/logform">
        <NoRawElements>ObjectModel ListStream BracketStream FormBin LogicalStream RawBracket PlatformRecords</NoRawElements>
        <PlatformEvidence>
          <LogForm source="mngcore_root-03-http_v8.1c.ru_8.2_managed-application_logform.xsd" root="Form/elements/command/property" elementCollections="event commands autoCommandBar"/>
          <CommandInterface source="mngcore_root-149-http_v8.1c.ru_8.2_managed-application_cmi.xsd" objects="CommandInfo CommandsInfo Command HandlerInfo"/>
        </PlatformEvidence>
      </PublicContract>
    </xs:appinfo>
  </xs:annotation>

  <xs:element name="Form" type="FormType"/>

  <xs:complexType name="FormType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Title" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="Width" type="xs:string" minOccurs="0"/>
      <xs:element name="Height" type="xs:string" minOccurs="0"/>
      <xs:element name="AutoTitle" type="xs:string" minOccurs="0"/>
      <xs:element name="Group" type="xs:string" minOccurs="0"/>
      <xs:element name="CommandBarLocation" type="xs:string" minOccurs="0"/>
      <xs:element name="VerticalScroll" type="xs:string" minOccurs="0"/>
      <xs:element name="ShowCommandBar" type="xs:string" minOccurs="0"/>
      <xs:element name="AutoCommandBar" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="SerializationCounter" type="xs:string" minOccurs="0"/>
      <xs:element name="RootPanelLayout" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="Events" type="EventsType" minOccurs="0"/>
      <xs:element name="Attributes" type="AttributesType" minOccurs="0"/>
      <xs:element name="ChildItems" type="ChildItemsType" minOccurs="0"/>
      <xs:element name="Commands" type="CommandsType" minOccurs="0"/>
    </xs:choice>
    <xs:attribute name="ordinaryFormVersion" type="xs:string" use="required"/>
    <xs:attribute name="containerCreatedTicks" type="xs:string" use="optional"/>
    <xs:attribute name="containerModifiedTicks" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="ChildItemsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="ActiveXControl" type="ControlType"/>
      <xs:element name="Button" type="ControlType"/>
      <xs:element name="CalendarField" type="ControlType"/>
      <xs:element name="Chart" type="ControlType"/>
      <xs:element name="CheckBox" type="ControlType"/>
      <xs:element name="ChoiceField" type="ControlType"/>
      <xs:element name="CommandBar" type="ControlType"/>
      <xs:element name="Dendrogram" type="ControlType"/>
      <xs:element name="DocumentField" type="ControlType"/>
      <xs:element name="FormattedDocumentField" type="ControlType"/>
      <xs:element name="GanttChart" type="ControlType"/>
      <xs:element name="GeographicalSchema" type="ControlType"/>
      <xs:element name="GeographicalSchemaField" type="ControlType"/>
      <xs:element name="GraphicalSchemaField" type="ControlType"/>
      <xs:element name="GroupBox" type="ControlType"/>
      <xs:element name="HTMLDocumentField" type="ControlType"/>
      <xs:element name="InputField" type="ControlType"/>
      <xs:element name="LabelDecoration" type="ControlType"/>
      <xs:element name="ListBox" type="ControlType"/>
      <xs:element name="Panel" type="ControlType"/>
      <xs:element name="Page" type="PageType"/>
      <xs:element name="PictureDecoration" type="ControlType"/>
      <xs:element name="PivotChart" type="ControlType"/>
      <xs:element name="ProgressBar" type="ControlType"/>
      <xs:element name="RadioButton" type="ControlType"/>
      <xs:element name="SpreadsheetDocumentField" type="ControlType"/>
      <xs:element name="Splitter" type="ControlType"/>
      <xs:element name="Table" type="ControlType"/>
      <xs:element name="TextDocumentField" type="ControlType"/>
      <xs:element name="TrackBar" type="ControlType"/>
      <xs:element name="UsualGroup" type="ControlType"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="PageType">
    <xs:sequence>
      <xs:element name="Title" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="ChildItems" type="ChildItemsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="ControlType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Action" type="AnyObjectType"/>
      <xs:element name="ActivePoint" type="AnyObjectType"/>
      <xs:element name="ActiveSeries" type="AnyObjectType"/>
      <xs:element name="AllowChangeColumnOrder" type="AnyObjectType"/>
      <xs:element name="AllowChangeRows" type="AnyObjectType"/>
      <xs:element name="AllowColumnSetup" type="AnyObjectType"/>
      <xs:element name="AllowDrag" type="AnyObjectType"/>
      <xs:element name="AllowDragStart" type="AnyObjectType"/>
      <xs:element name="AlternateRowColors" type="AnyObjectType"/>
      <xs:element name="AlternatingRowBackColor" type="AnyObjectType"/>
      <xs:element name="AutoContextMenu" type="AnyObjectType"/>
      <xs:element name="AutoInsertNewRow" type="AnyObjectType"/>
      <xs:element name="AutoMarkIncomplete" type="AnyObjectType"/>
      <xs:element name="AutoMaxHeight" type="AnyObjectType"/>
      <xs:element name="AutoMaxWidth" type="AnyObjectType"/>
      <xs:element name="AutoMaximumValue" type="AnyObjectType"/>
      <xs:element name="AutoMinimumValue" type="AnyObjectType"/>
      <xs:element name="AutoPointText" type="AnyObjectType"/>
      <xs:element name="AutoSelectIncomplete" type="AnyObjectType"/>
      <xs:element name="AutoSeriesSpread" type="AnyObjectType"/>
      <xs:element name="AutoSeriesText" type="AnyObjectType"/>
      <xs:element name="AutoTranspose" type="AnyObjectType"/>
      <xs:element name="AutoTraversalOrder" type="AnyObjectType"/>
      <xs:element name="Autofill" type="AnyObjectType"/>
      <xs:element name="Auxiliary" type="AnyObjectType"/>
      <xs:element name="BackColor" type="AnyObjectType"/>
      <xs:element name="BaseValue" type="AnyObjectType"/>
      <xs:element name="BigStep" type="AnyObjectType"/>
      <xs:element name="Border" type="AnyObjectType"/>
      <xs:element name="BorderColor" type="AnyObjectType"/>
      <xs:element name="ButtonAlignment" type="AnyObjectType"/>
      <xs:element name="ButtonBackColor" type="AnyObjectType"/>
      <xs:element name="ButtonTextColor" type="AnyObjectType"/>
      <xs:element name="ButtonType" type="AnyObjectType"/>
      <xs:element name="Buttons" type="AnyObjectType"/>
      <xs:element name="CalendarNavigation" type="AnyObjectType"/>
      <xs:element name="CancelButton" type="AnyObjectType"/>
      <xs:element name="ChartKind" type="AnyObjectType"/>
      <xs:element name="ChildItems" type="ChildItemsType"/>
      <xs:element name="ChoiceButton" type="AnyObjectType"/>
      <xs:element name="ChoiceButtonPicture" type="AnyObjectType"/>
      <xs:element name="ChoiceList" type="AnyObjectType"/>
      <xs:element name="ChoiceListButton" type="AnyObjectType"/>
      <xs:element name="ChoiceListHeight" type="AnyObjectType"/>
      <xs:element name="ChoiceListMode" type="AnyObjectType"/>
      <xs:element name="ChoiceListWidth" type="AnyObjectType"/>
      <xs:element name="ChoiceMode" type="AnyObjectType"/>
      <xs:element name="ClearButton" type="AnyObjectType"/>
      <xs:element name="Clsid" type="AnyObjectType"/>
      <xs:element name="ColorPalette" type="AnyObjectType"/>
      <xs:element name="Columns" type="AnyObjectType"/>
      <xs:element name="ColumnsCount" type="AnyObjectType"/>
      <xs:element name="CommandName" type="AnyObjectType"/>
      <xs:element name="CommandSource" type="AnyObjectType"/>
      <xs:element name="ContextMenu" type="AnyObjectType"/>
      <xs:element name="CreateButton" type="AnyObjectType"/>
      <xs:element name="CurrentColumn" type="AnyObjectType"/>
      <xs:element name="CurrentData" type="AnyObjectType"/>
      <xs:element name="CurrentDate" type="AnyObjectType"/>
      <xs:element name="CurrentItem" type="AnyObjectType"/>
      <xs:element name="CurrentPage" type="AnyObjectType"/>
      <xs:element name="CurrentParent" type="AnyObjectType"/>
      <xs:element name="CurrentRow" type="AnyObjectType"/>
      <xs:element name="DataBindingFlag" type="AnyObjectType"/>
      <xs:element name="DataBindingMode" type="AnyObjectType"/>
      <xs:element name="DataPath" type="AnyObjectType"/>
      <xs:element name="DataValue" type="AnyObjectType"/>
      <xs:element name="DefaultAction" type="AnyObjectType"/>
      <xs:element name="DefaultButton" type="AnyObjectType"/>
      <xs:element name="DisplayStyle" type="AnyObjectType"/>
      <xs:element name="DisplayedArea" type="AnyObjectType"/>
      <xs:element name="DistributeByPages" type="AnyObjectType"/>
      <xs:element name="Document" type="AnyObjectType"/>
      <xs:element name="EditButton" type="AnyObjectType"/>
      <xs:element name="EditMode" type="AnyObjectType"/>
      <xs:element name="Editing" type="AnyObjectType"/>
      <xs:element name="Enabled" type="AnyObjectType"/>
      <xs:element name="Events" type="AnyObjectType"/>
      <xs:element name="ExtendedEdit" type="AnyObjectType"/>
      <xs:element name="ExtendedTooltip" type="AnyObjectType"/>
      <xs:element name="FieldBackColor" type="AnyObjectType"/>
      <xs:element name="FieldTextColor" type="AnyObjectType"/>
      <xs:element name="Fields" type="AnyObjectType"/>
      <xs:element name="FirstInGroup" type="AnyObjectType"/>
      <xs:element name="Font" type="AnyObjectType"/>
      <xs:element name="Footer" type="AnyObjectType"/>
      <xs:element name="FooterBackColor" type="AnyObjectType"/>
      <xs:element name="FooterFont" type="AnyObjectType"/>
      <xs:element name="FooterHeight" type="AnyObjectType"/>
      <xs:element name="FooterTextColor" type="AnyObjectType"/>
      <xs:element name="Format" type="AnyObjectType"/>
      <xs:element name="GaugeBands" type="AnyObjectType"/>
      <xs:element name="GaugeEndAngle" type="AnyObjectType"/>
      <xs:element name="GaugeHubColor" type="AnyObjectType"/>
      <xs:element name="GaugeHubThickness" type="AnyObjectType"/>
      <xs:element name="GaugeScaleLabelsAlongScale" type="AnyObjectType"/>
      <xs:element name="GaugeScaleLabelsPosition" type="AnyObjectType"/>
      <xs:element name="GaugeScaleThickness" type="AnyObjectType"/>
      <xs:element name="GaugeStartAngle" type="AnyObjectType"/>
      <xs:element name="GaugeValueDisplay" type="AnyObjectType"/>
      <xs:element name="Gradient" type="AnyObjectType"/>
      <xs:element name="Header" type="AnyObjectType"/>
      <xs:element name="HeaderBackColor" type="AnyObjectType"/>
      <xs:element name="HeaderFont" type="AnyObjectType"/>
      <xs:element name="HeaderHeight" type="AnyObjectType"/>
      <xs:element name="HeaderTextColor" type="AnyObjectType"/>
      <xs:element name="Height" type="AnyObjectType"/>
      <xs:element name="HighlightNegative" type="AnyObjectType"/>
      <xs:element name="HorizontalAlign" type="AnyObjectType"/>
      <xs:element name="HorizontalLines" type="AnyObjectType"/>
      <xs:element name="HorizontalScrollBar" type="AnyObjectType"/>
      <xs:element name="HorizontalStretch" type="AnyObjectType"/>
      <xs:element name="Hyperlink" type="AnyObjectType"/>
      <xs:element name="IncompleteChoice" type="AnyObjectType"/>
      <xs:element name="IncompleteChoiceMode" type="AnyObjectType"/>
      <xs:element name="IncompleteMark" type="AnyObjectType"/>
      <xs:element name="InitialListView" type="AnyObjectType"/>
      <xs:element name="InitialTreeView" type="AnyObjectType"/>
      <xs:element name="InputRowsMode" type="AnyObjectType"/>
      <xs:element name="Items" type="AnyObjectType"/>
      <xs:element name="LabelPercentFormat" type="AnyObjectType"/>
      <xs:element name="LabelValueFormat" type="AnyObjectType"/>
      <xs:element name="LabelsBackColor" type="AnyObjectType"/>
      <xs:element name="LabelsBorder" type="AnyObjectType"/>
      <xs:element name="LabelsBorderColor" type="AnyObjectType"/>
      <xs:element name="LabelsFont" type="AnyObjectType"/>
      <xs:element name="LabelsPosition" type="AnyObjectType"/>
      <xs:element name="LabelsSeparator" type="AnyObjectType"/>
      <xs:element name="LabelsTextColor" type="AnyObjectType"/>
      <xs:element name="LabelsView" type="AnyObjectType"/>
      <xs:element name="LeftFixedColumns" type="AnyObjectType"/>
      <xs:element name="LegendArea" type="AnyObjectType"/>
      <xs:element name="Light" type="AnyObjectType"/>
      <xs:element name="MarkStep" type="AnyObjectType"/>
      <xs:element name="Marquee" type="AnyObjectType"/>
      <xs:element name="Mask" type="AnyObjectType"/>
      <xs:element name="MaxHeight" type="AnyObjectType"/>
      <xs:element name="MaxLength" type="AnyObjectType"/>
      <xs:element name="MaxSeries" type="AnyObjectType"/>
      <xs:element name="MaxSeriesCount" type="AnyObjectType"/>
      <xs:element name="MaxSeriesPercent" type="AnyObjectType"/>
      <xs:element name="MaxValue" type="AnyObjectType"/>
      <xs:element name="MaxWidth" type="AnyObjectType"/>
      <xs:element name="MaximumValue" type="AnyObjectType"/>
      <xs:element name="MenuMode" type="AnyObjectType"/>
      <xs:element name="MinValue" type="AnyObjectType"/>
      <xs:element name="MinWidth" type="AnyObjectType"/>
      <xs:element name="MinimumValue" type="AnyObjectType"/>
      <xs:element name="MultiLine" type="AnyObjectType"/>
      <xs:element name="OpenButton" type="AnyObjectType"/>
      <xs:element name="Orientation" type="AnyObjectType"/>
      <xs:element name="Outline" type="AnyObjectType"/>
      <xs:element name="Output" type="AnyObjectType"/>
      <xs:element name="PagesRepresentation" type="AnyObjectType"/>
      <xs:element name="PanelLayout" type="AnyObjectType"/>
      <xs:element name="PanelPicturePosition" type="AnyObjectType"/>
      <xs:element name="PasswordMode" type="AnyObjectType"/>
      <xs:element name="PeriodEnd" type="AnyObjectType"/>
      <xs:element name="PeriodStart" type="AnyObjectType"/>
      <xs:element name="PeriodicVariantMultiplicity" type="AnyObjectType"/>
      <xs:element name="PeriodicVariantUnit" type="AnyObjectType"/>
      <xs:element name="Picture" type="AnyObjectType"/>
      <xs:element name="PicturePosition" type="AnyObjectType"/>
      <xs:element name="PictureRendering" type="AnyObjectType"/>
      <xs:element name="PictureSize" type="AnyObjectType"/>
      <xs:element name="PictureStyle" type="AnyObjectType"/>
      <xs:element name="PivotChartKind" type="AnyObjectType"/>
      <xs:element name="PivotSeries" type="AnyObjectType"/>
      <xs:element name="PlotArea" type="AnyObjectType"/>
      <xs:element name="Points" type="AnyObjectType"/>
      <xs:element name="PointsCount" type="AnyObjectType"/>
      <xs:element name="Position" type="AnyObjectType"/>
      <xs:element name="ReadOnly" type="AnyObjectType"/>
      <xs:element name="Refresh" type="AnyObjectType"/>
      <xs:element name="RegulationButton" type="AnyObjectType"/>
      <xs:element name="Representation" type="AnyObjectType"/>
      <xs:element name="RightFixedColumns" type="AnyObjectType"/>
      <xs:element name="RowSelectionMode" type="AnyObjectType"/>
      <xs:element name="Rows" type="AnyObjectType"/>
      <xs:element name="RowsCount" type="AnyObjectType"/>
      <xs:element name="Scale" type="AnyObjectType"/>
      <xs:element name="ScalePicture" type="AnyObjectType"/>
      <xs:element name="ScaleSupport" type="AnyObjectType"/>
      <xs:element name="ScrollablePagesMode" type="AnyObjectType"/>
      <xs:element name="SelectedDates" type="AnyObjectType"/>
      <xs:element name="SelectedRows" type="AnyObjectType"/>
      <xs:element name="SelectedText" type="AnyObjectType"/>
      <xs:element name="SelectionBackColor" type="AnyObjectType"/>
      <xs:element name="SelectionMode" type="AnyObjectType"/>
      <xs:element name="SelectionTextColor" type="AnyObjectType"/>
      <xs:element name="Series" type="AnyObjectType"/>
      <xs:element name="SeriesCount" type="AnyObjectType"/>
      <xs:element name="SeriesInRows" type="AnyObjectType"/>
      <xs:element name="Shortcut" type="AnyObjectType"/>
      <xs:element name="ShowCurrentDate" type="AnyObjectType"/>
      <xs:element name="ShowLegend" type="AnyObjectType"/>
      <xs:element name="ShowMark" type="AnyObjectType"/>
      <xs:element name="ShowPercent" type="AnyObjectType"/>
      <xs:element name="ShowPicture" type="AnyObjectType"/>
      <xs:element name="ShowSelection" type="AnyObjectType"/>
      <xs:element name="ShowTitle" type="AnyObjectType"/>
      <xs:element name="SkipBaseValue" type="AnyObjectType"/>
      <xs:element name="SkipOnInput" type="AnyObjectType"/>
      <xs:element name="SourceData" type="AnyObjectType"/>
      <xs:element name="SpaceMode" type="AnyObjectType"/>
      <xs:element name="State" type="AnyObjectType"/>
      <xs:element name="Step" type="AnyObjectType"/>
      <xs:element name="TextColor" type="AnyObjectType"/>
      <xs:element name="TextEditing" type="AnyObjectType"/>
      <xs:element name="TextPosition" type="AnyObjectType"/>
      <xs:element name="ThreeState" type="AnyObjectType"/>
      <xs:element name="Title" type="AnyObjectType"/>
      <xs:element name="TitleArea" type="AnyObjectType"/>
      <xs:element name="ToolTip" type="AnyObjectType"/>
      <xs:element name="TransparentBackColor" type="AnyObjectType"/>
      <xs:element name="TransparentLabelsBackColor" type="AnyObjectType"/>
      <xs:element name="TraversalOrder" type="AnyObjectType"/>
      <xs:element name="Type" type="AnyObjectType"/>
      <xs:element name="TypeChoice" type="AnyObjectType"/>
      <xs:element name="TypeLinkElement" type="AnyObjectType"/>
      <xs:element name="TypeRestriction" type="AnyObjectType"/>
      <xs:element name="UnselectedPictureText" type="AnyObjectType"/>
      <xs:element name="ValueType" type="AnyObjectType"/>
      <xs:element name="VerticalAlign" type="AnyObjectType"/>
      <xs:element name="VerticalLines" type="AnyObjectType"/>
      <xs:element name="VerticalScrollBar" type="AnyObjectType"/>
      <xs:element name="VerticalStretch" type="AnyObjectType"/>
      <xs:element name="ViewSetupMode" type="AnyObjectType"/>
      <xs:element name="Visible" type="AnyObjectType"/>
      <xs:element name="WeekendTextColor" type="AnyObjectType"/>
      <xs:element name="Width" type="AnyObjectType"/>
      <xs:element name="WordWrap" type="AnyObjectType"/>
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
    <xs:attribute name="uuid" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence>
      <xs:element name="Event" type="EventType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="optional"/>
        <xs:attribute name="uuid" type="xs:string" use="optional"/>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:anyAttribute processContents="lax"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="AttributesType">
    <xs:sequence>
      <xs:element name="Attribute" type="AnyObjectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="CommandsType">
    <xs:sequence>
      <xs:element name="Command" type="AnyObjectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="AnyObjectType" mixed="true">
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>
</xs:schema>
