<?xml version='1.0' encoding='utf-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation>Ordinary Form.xml v2 public object model. The shape follows managed form XML: Form root, Events, ChildItems, Attributes, Commands, named controls, and nested ChildItems. Platform list-stream/bracket internals are implementation details and must not be exposed in this XML.</xs:documentation>
    <xs:appinfo>
      <PublicContract version="2.0-draft" styleReference="http://v8.1c.ru/8.3/xcf/logform">
        <NoRawElements>ObjectModel ListStream BracketStream FormBin LogicalStream RawBracket PlatformRecords</NoRawElements>
        <PlatformEvidence>
          <LogForm source="mngcore_root-03-http_v8.1c.ru_8.2_managed-application_logform.xsd" root="Form/elements/command/property" elementCollections="event commands autoCommandBar"/>
          <CommandInterface source="mngcore_root-149-http_v8.1c.ru_8.2_managed-application_cmi.xsd" objects="CommandInfo CommandsInfo Command HandlerInfo"/>
        </PlatformEvidence>
      </PublicContract>
    </xs:appinfo>
  </xs:annotation>

  <xs:element name="Form" type="FormType"/>

  <xs:complexType name="FormType">
    <xs:sequence>
      <xs:element name="Title" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="Width" type="xs:string" minOccurs="0"/>
      <xs:element name="Height" type="xs:string" minOccurs="0"/>
      <xs:element name="AutoTitle" type="xs:string" minOccurs="0"/>
      <xs:element name="Group" type="xs:string" minOccurs="0"/>
      <xs:element name="CommandBarLocation" type="xs:string" minOccurs="0"/>
      <xs:element name="VerticalScroll" type="xs:string" minOccurs="0"/>
      <xs:element name="ShowCommandBar" type="xs:string" minOccurs="0"/>
      <xs:element name="AutoCommandBar" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="Events" type="EventsType" minOccurs="0"/>
      <xs:element name="ChildItems" type="ChildItemsType" minOccurs="0"/>
      <xs:element name="Attributes" type="AttributesType" minOccurs="0"/>
      <xs:element name="Commands" type="CommandsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="ordinaryFormVersion" type="xs:string" use="required"/>
    <xs:attribute name="containerCreatedTicks" type="xs:string" use="optional"/>
    <xs:attribute name="containerModifiedTicks" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="ChildItemsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="ActiveXControl" type="ControlType"/>
      <xs:element name="Button" type="ControlType"/>
      <xs:element name="CalendarField" type="ControlType"/>
      <xs:element name="Chart" type="ControlType"/>
      <xs:element name="CheckBox" type="ControlType"/>
      <xs:element name="ChoiceField" type="ControlType"/>
      <xs:element name="CommandBar" type="ControlType"/>
      <xs:element name="DocumentField" type="ControlType"/>
      <xs:element name="FormattedDocumentField" type="ControlType"/>
      <xs:element name="GeographicalSchema" type="ControlType"/>
      <xs:element name="HTMLDocumentField" type="ControlType"/>
      <xs:element name="InputField" type="ControlType"/>
      <xs:element name="LabelDecoration" type="ControlType"/>
      <xs:element name="Panel" type="ControlType"/>
      <xs:element name="Page" type="PageType"/>
      <xs:element name="PictureDecoration" type="ControlType"/>
      <xs:element name="PivotChart" type="ControlType"/>
      <xs:element name="ProgressBar" type="ControlType"/>
      <xs:element name="RadioButton" type="ControlType"/>
      <xs:element name="SpreadsheetDocumentField" type="ControlType"/>
      <xs:element name="Splitter" type="ControlType"/>
      <xs:element name="Table" type="ControlType"/>
      <xs:element name="TextDocumentField" type="ControlType"/>
      <xs:element name="UsualGroup" type="ControlType"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="PageType">
    <xs:sequence>
      <xs:element name="Title" type="AnyObjectType" minOccurs="0"/>
      <xs:element name="ChildItems" type="ChildItemsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="ControlType">
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
    <xs:attribute name="uuid" type="xs:string" use="optional"/>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="PagesType">
    <xs:sequence>
      <xs:element name="Page" type="PageType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence>
      <xs:element name="Event" type="EventType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="optional"/>
        <xs:attribute name="uuid" type="xs:string" use="optional"/>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:anyAttribute processContents="lax"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="AttributesType">
    <xs:sequence>
      <xs:element name="Attribute" type="AnyObjectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="CommandsType">
    <xs:sequence>
      <xs:element name="Command" type="AnyObjectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="AnyObjectType" mixed="true">
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:anyAttribute processContents="lax"/>
  </xs:complexType>
</xs:schema>
