<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation>Generated bilingual annotations for the ordinary-form metamodel.</xs:documentation>
    <xs:appinfo>
      <Palette ordinaryFormVersion="2.1">
        <Form>
          <Properties>
            <Property name="AutoTitle" apiName="AutoTitle" russianName="АвтоЗаголовок" russianType="Булево" valueCodec="boolean"/>
            <Property name="FormOwner" apiName="FormOwner" russianName="ВладелецФормы" russianType="Форма ; Элемент управления" valueCodec="unclassified"/>
            <Property name="Height" apiName="Height" russianName="Высота" russianType="Число" valueCodec="decimal"/>
            <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
            <Property name="CloseOnChoice" apiName="CloseOnChoice" russianName="ЗакрыватьПриВыборе" russianType="Булево" valueCodec="boolean"/>
            <Property name="CloseOnOwnerClose" apiName="CloseOnOwnerClose" russianName="ЗакрыватьПриЗакрытииВладельца" russianType="Булево" valueCodec="boolean"/>
            <Property name="SizeChange" apiName="SizeChange" russianName="ИзменениеРазмера" russianType="ИзменениеРазмераОкна" valueCodec="enumeration"/>
            <Property name="ChangeWindowAppearanceMode" apiName="ChangeWindowAppearanceMode" russianName="ИзменятьСпособОтображенияОкна" russianType="ИзменениеСпособаОтображенияОкна" valueCodec="enumeration"/>
            <Property name="WindowOptionsName" apiName="WindowOptionsName" russianName="ИмяСохраненияПоложенияОкна" russianType="Строка" valueCodec="string"/>
            <Property name="CaptionPicture" apiName="CaptionPicture" russianName="КартинкаЗаголовка" russianType="Картинка" valueCodec="picture"/>
            <Property name="WindowOptionsKey" apiName="WindowOptionsKey" russianName="КлючСохраненияПоложенияОкна" russianType="Строка" valueCodec="string"/>
            <Property name="UniqueKey" apiName="UniqueKey" russianName="КлючУникальности" russianType="Произвольный" valueCodec="unclassified"/>
            <Property name="MultipleChoice" apiName="MultipleChoice" russianName="МножественныйВыбор" russianType="Булево" valueCodec="boolean"/>
            <Property name="ModalMode" apiName="ModalMode" russianName="МодальныйРежим" russianType="Булево" valueCodec="boolean"/>
            <Property name="Modified" apiName="Modified" russianName="Модифицированность" russianType="Булево" valueCodec="boolean"/>
            <Property name="ChoiceInitialValue" apiName="ChoiceInitialValue" russianName="НачальноеЗначениеВыбора" russianType="Произвольный" valueCodec="unclassified"/>
            <Property name="Panel" apiName="Panel" russianName="Панель" russianType="Панель" valueCodec="unclassified"/>
            <Property name="EnterKeyBehavior" apiName="EnterKeyBehavior" russianName="ПоведениеКлавишиEnter" russianType="ТипПоведенияКлавишиEnter" valueCodec="enumeration"/>
            <Property name="WindowLocation" apiName="WindowLocation" russianName="ПоложениеОкна" russianType="ВариантПоложенияОкна" valueCodec="enumeration"/>
            <Property name="WindowDockLocation" apiName="WindowDockLocation" russianName="ПоложениеПрикрепленногоОкна" russianType="ВариантПрикрепленияОкна" valueCodec="enumeration"/>
            <Property name="AllowClose" apiName="AllowClose" russianName="РазрешитьЗакрытие" russianType="Булево" valueCodec="boolean"/>
            <Property name="AllowJoinWindow" apiName="AllowJoinWindow" russianName="РазрешитьСоединятьОкно" russianType="Булево" valueCodec="boolean"/>
            <Property name="AllowNormalState" apiName="AllowNormalState" russianName="РазрешитьСостояниеОбычное" russianType="Булево" valueCodec="boolean"/>
            <Property name="AllowDockedState" apiName="AllowDockedState" russianName="РазрешитьСостояниеПрикрепленное" russianType="Булево" valueCodec="boolean"/>
            <Property name="AllowAutohideState" apiName="AllowAutohideState" russianName="РазрешитьСостояниеПрячущееся" russianType="Булево" valueCodec="boolean"/>
            <Property name="AllowFloatState" apiName="AllowFloatState" russianName="РазрешитьСостояниеСвободное" russianType="Булево" valueCodec="boolean"/>
            <Property name="ChoiceMode" apiName="ChoiceMode" russianName="РежимВыбора" russianType="Булево" valueCodec="boolean"/>
            <Property name="DesktopMode" apiName="DesktopMode" russianName="РежимРабочегоСтола" russianType="Булево" valueCodec="boolean"/>
            <Property name="ConnectableWindow" apiName="ConnectableWindow" russianName="СоединяемоеОкно" russianType="Булево" valueCodec="boolean"/>
            <Property name="WindowState" apiName="WindowState" russianName="СостояниеОкна" russianType="ВариантСостоянияОкна" valueCodec="enumeration"/>
            <Property name="WindowAppearanceMode" apiName="WindowAppearanceMode" russianName="СпособОтображенияОкна" russianType="ВариантСпособаОтображенияОкна" valueCodec="enumeration"/>
            <Property name="Style" apiName="Style" russianName="Стиль" russianType="Стиль" valueCodec="unclassified"/>
            <Property name="CurrentControl" apiName="CurrentControl" russianName="ТекущийЭлемент" russianType="" valueCodec="unclassified"/>
            <Property name="ReadOnly" apiName="ReadOnly" russianName="ТолькоПросмотр" russianType="Булево" valueCodec="boolean"/>
            <Property name="Width" apiName="Width" russianName="Ширина" russianType="Число" valueCodec="decimal"/>
            <Property name="Controls" apiName="Controls" russianName="ЭлементыФормы" russianType="ЭлементыФормы" valueCodec="unclassified"/>
            <Property name="ThisForm" apiName="ThisForm" russianName="ЭтаФорма" russianType="Форма" valueCodec="unclassified"/>
          </Properties>
          <Events>
            <Event name="ExternalEvent" apiName="ExternalEvent" russianName="ВнешнееСобытие"/>
            <Event name="RefreshDisplay" apiName="RefreshDisplay" russianName="ОбновлениеОтображения"/>
            <Event name="ObjectActivationProcessing" apiName="ObjectActivationProcessing" russianName="ОбработкаАктивизацииОбъекта"/>
            <Event name="ChoiceProcessing" apiName="ChoiceProcessing" russianName="ОбработкаВыбора"/>
            <Event name="NewObjectWriteProcessing" apiName="NewObjectWriteProcessing" russianName="ОбработкаЗаписиНовогоОбъекта"/>
            <Event name="NotificationProcessing" apiName="NotificationProcessing" russianName="ОбработкаОповещения"/>
            <Event name="FillCheckProcessing" apiName="FillCheckProcessing" russianName="ОбработкаПроверкиЗаполнения"/>
            <Event name="AddInDetachmentOnError" apiName="AddInDetachmentOnError" russianName="ОтключениеВнешнейКомпонентыПриОшибке"/>
            <Event name="BeforeClose" apiName="BeforeClose" russianName="ПередЗакрытием"/>
            <Event name="BeforeOpen" apiName="BeforeOpen" russianName="ПередОткрытием"/>
            <Event name="OnClose" apiName="OnClose" russianName="ПриЗакрытии"/>
            <Event name="OnOpen" apiName="OnOpen" russianName="ПриОткрытии"/>
            <Event name="OnReopen" apiName="OnReopen" russianName="ПриПовторномОткрытии"/>
          </Events>
        </Form>
        <SharedProperties surface="controlExtension">
          <Property name="AutoContextMenu" apiName="AutoContextMenu" russianName="АвтоКонтекстноеМеню" russianType="Булево" valueCodec="boolean"/>
          <Property name="Data" apiName="Data" russianName="Данные" russianType="Строка" valueCodec="string"/>
          <Property name="Value" apiName="Value" russianName="Значение" russianType="" valueCodec="unclassified"/>
          <Property name="ModifiesData" apiName="ModifiesData" russianName="ИзменяетДанные" russianType="Булево" valueCodec="boolean"/>
          <Property name="Name" apiName="Name" russianName="Имя" russianType="Строка" valueCodec="string"/>
          <Property name="ActionSource" apiName="ActionSource" russianName="ИсточникДействий" russianType="" valueCodec="unclassified"/>
          <Property name="DefaultButton" apiName="DefaultButton" russianName="КнопкаПоУмолчанию" russianType="Булево" valueCodec="boolean"/>
          <Property name="ContextMenu" apiName="ContextMenu" russianName="КонтекстноеМеню" russianType="Неопределено ; КоманднаяПанель ; КнопкаКоманднойПанели" valueCodec="unclassified"/>
          <Property name="FirstInGroup" apiName="FirstInGroup" russianName="ПервыйВГруппе" russianType="Булево" valueCodec="boolean"/>
          <Property name="SkipOnInput" apiName="SkipOnInput" russianName="ПропускатьПриВводе" russianType="Булево" valueCodec="boolean"/>
          <Property name="ValueType" apiName="ValueType" russianName="ТипЗначения" russianType="ОписаниеТипов" valueCodec="type-domain"/>
        </SharedProperties>
        <SharedProperties surface="panelPlacement">
          <Property name="DefaultControl" apiName="DefaultControl" russianName="АктивизироватьПоУмолчанию" russianType="Булево" valueCodec="boolean"/>
          <Property name="Top" apiName="Top" russianName="Верх" russianType="Число" valueCodec="decimal"/>
          <Property name="Visible" apiName="Visible" russianName="Видимость" russianType="Булево" valueCodec="boolean"/>
          <Property name="Height" apiName="Height" russianName="Высота" russianType="Число" valueCodec="decimal"/>
          <Property name="Left" apiName="Left" russianName="Лево" russianType="Число" valueCodec="decimal"/>
          <Property name="TabOrder" apiName="TabOrder" russianName="ПорядокОбхода" russianType="Число" valueCodec="decimal"/>
          <Property name="ZOrder" apiName="ZOrder" russianName="ПорядокОтображения" russianType="Число" valueCodec="decimal"/>
          <Property name="Collapse" apiName="Collapse" russianName="Свертка" russianType="РежимСверткиЭлементаУправления" valueCodec="enumeration"/>
          <Property name="Width" apiName="Width" russianName="Ширина" russianType="Число" valueCodec="decimal"/>
        </SharedProperties>
        <Controls>
          <Control name="Panel" apiName="Panel" russianName="Панель" children="controlsAndPages">
            <Properties>
              <Property name="AutoTabOrder" apiName="AutoTabOrder" russianName="АвтоПорядокОбхода" russianType="Булево" valueCodec="boolean"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="ShowTabs" apiName="ShowTabs" russianName="ОтображениеЗакладок" russianType="ОтображениеЗакладок" valueCodec="enumeration"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="PanelPictureLocation" apiName="PanelPictureLocation" russianName="ПоложениеКартинкиПанели" russianType="ПоложениеКартинкиПанели" valueCodec="enumeration"/>
              <Property name="TabOrder" apiName="TabOrder" russianName="ПорядокОбхода" russianType="Число" valueCodec="decimal"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="PictureSize" apiName="PictureSize" russianName="РазмерКартинки" russianType="РазмерКартинки" valueCodec="enumeration"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="SeparateByPage" apiName="SeparateByPage" russianName="РаспределятьПоСтраницам" russianType="Булево" valueCodec="boolean"/>
              <Property name="ScrollPageMode" apiName="ScrollPageMode" russianName="РежимПрокручиваемыхСтраниц" russianType="Булево" valueCodec="boolean"/>
              <Property name="Pages" apiName="Pages" russianName="Страницы" russianType="СтраницыПанели" valueCodec="unclassified"/>
              <Property name="CurrentPage" apiName="CurrentPage" russianName="ТекущаяСтраница" russianType="СтраницаПанели" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="OnCurrentPageChange" apiName="OnCurrentPageChange" russianName="ПриСменеСтраницы"/>
            </Events>
          </Control>
          <Control name="CommandBar" apiName="CommandBar" russianName="КоманднаяПанель" children="none">
            <Properties>
              <Property name="AutoFill" apiName="AutoFill" russianName="АвтоЗаполнение" russianType="Булево" valueCodec="boolean"/>
              <Property name="Secondary" apiName="Secondary" russianName="Вспомогательная" russianType="Булево" valueCodec="boolean"/>
              <Property name="ButtonsAlignment" apiName="ButtonsAlignment" russianName="ВыравниваниеКнопок" russianType="ВыравниваниеКнопокКоманднойПанели" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Buttons" apiName="Buttons" russianName="Кнопки" russianType="КнопкиКоманднойПанели" valueCodec="unclassified"/>
              <Property name="Orientation" apiName="Orientation" russianName="Ориентация" russianType="Ориентация" valueCodec="enumeration"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonTextColor" apiName="ButtonTextColor" russianName="ЦветТекстаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
            </Events>
          </Control>
          <Control name="Button" apiName="Button" russianName="Кнопка" children="none">
            <Properties>
              <Property name="VerticalAlign" apiName="VerticalAlign" russianName="ВертикальноеПоложение" russianType="ВертикальноеПоложение" valueCodec="enumeration"/>
              <Property name="HorizontalAlign" apiName="HorizontalAlign" russianName="ГоризонтальноеПоложение" russianType="ГоризонтальноеПоложение" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="Buttons" apiName="Buttons" russianName="Кнопки" russianType="КнопкиКоманднойПанели" valueCodec="unclassified"/>
              <Property name="MultiLine" apiName="MultiLine" russianName="МногострочныйРежим" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="PictureLocation" apiName="PictureLocation" russianName="ПоложениеКартинки" russianType="ПоложениеКартинкиКнопки" valueCodec="enumeration"/>
              <Property name="PictureSize" apiName="PictureSize" russianName="РазмерКартинки" russianType="РазмерКартинки" valueCodec="enumeration"/>
              <Property name="MenuMode" apiName="MenuMode" russianName="РежимМеню" russianType="ИспользованиеРежимаМеню" valueCodec="enumeration"/>
              <Property name="Shortcut" apiName="Shortcut" russianName="СочетаниеКлавиш" russianType="СочетаниеКлавиш" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonTextColor" apiName="ButtonTextColor" russianName="ЦветТекстаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Click" apiName="Click" russianName="Нажатие"/>
            </Events>
          </Control>
          <Control name="PictureDecoration" apiName="PictureBox" russianName="ПолеКартинки" children="none">
            <Properties>
              <Property name="Hyperlink" apiName="Hyperlink" russianName="Гиперссылка" russianType="Булево" valueCodec="boolean"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="UseContextMenu" apiName="UseContextMenu" russianName="ИспользоватьКонтекстноеМеню" russianType="Булево" valueCodec="boolean"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="Zoomable" apiName="Zoomable" russianName="Масштабировать" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="PictureSize" apiName="PictureSize" russianName="РазмерКартинки" russianType="РазмерКартинки" valueCodec="enumeration"/>
              <Property name="EnableStartDrag" apiName="EnableStartDrag" russianName="РазрешитьНачалоПеретаскивания" russianType="Булево" valueCodec="boolean"/>
              <Property name="EnableDrag" apiName="EnableDrag" russianName="РазрешитьПеретаскивание" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="Shortcut" apiName="Shortcut" russianName="СочетаниеКлавиш" russianType="СочетаниеКлавиш" valueCodec="unclassified"/>
              <Property name="NonselectedPictureText" apiName="NonselectedPictureText" russianName="ТекстНевыбраннойКартинки" russianType="Строка" valueCodec="string"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Click" apiName="Click" russianName="Нажатие"/>
              <Event name="DragStart" apiName="DragStart" russianName="НачалоПеретаскивания"/>
              <Event name="DragEnd" apiName="DragEnd" russianName="ОкончаниеПеретаскивания"/>
              <Event name="Drag" apiName="Drag" russianName="Перетаскивание"/>
              <Event name="DragCheck" apiName="DragCheck" russianName="ПроверкаПеретаскивания"/>
            </Events>
          </Control>
          <Control name="CheckBox" apiName="CheckBox" russianName="Флажок" children="none">
            <Properties>
              <Property name="VerticalAlign" apiName="VerticalAlign" russianName="ВертикальноеПоложение" russianType="ВертикальноеПоложение" valueCodec="enumeration"/>
              <Property name="HorizontalAlign" apiName="HorizontalAlign" russianName="ГоризонтальноеПоложение" russianType="ГоризонтальноеПоложение" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="TitleLocation" apiName="TitleLocation" russianName="ПоложениеЗаголовка" russianType="ПоложениеЗаголовка" valueCodec="enumeration"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="ThreeState" apiName="ThreeState" russianName="ТриСостояния" russianType="Булево" valueCodec="boolean"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
            </Events>
          </Control>
          <Control name="ChoiceField" apiName="ComboBox" russianName="ПолеВыбора" children="none">
            <Properties>
              <Property name="ChoiceListHeight" apiName="ChoiceListHeight" russianName="ВысотаСпискаВыбора" russianType="Число" valueCodec="decimal"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="SelButtonPicture" apiName="SelButtonPicture" russianName="КартинкаКнопкиВыбора" russianType="Картинка" valueCodec="picture"/>
              <Property name="ChoiceButtonPicture" apiName="ChoiceButtonPicture" russianName="КартинкаКнопкиВыбора" russianType="Картинка" valueCodec="picture"/>
              <Property name="ChoiceButton" apiName="ChoiceButton" russianName="КнопкаВыбора" russianType="Булево" valueCodec="boolean"/>
              <Property name="OpenButton" apiName="OpenButton" russianName="КнопкаОткрытия" russianType="Булево" valueCodec="boolean"/>
              <Property name="ClearButton" apiName="ClearButton" russianName="КнопкаОчистки" russianType="Булево" valueCodec="boolean"/>
              <Property name="SpinButton" apiName="SpinButton" russianName="КнопкаРегулирования" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="ChoiceList" apiName="ChoiceList" russianName="СписокВыбора" russianType="СписокЗначений" valueCodec="unclassified"/>
              <Property name="ReadOnly" apiName="ReadOnly" russianName="ТолькоПросмотр" russianType="Булево" valueCodec="boolean"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonTextColor" apiName="ButtonTextColor" russianName="ЦветТекстаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="ChoiceListWidth" apiName="ChoiceListWidth" russianName="ШиринаСпискаВыбора" russianType="Число" valueCodec="decimal"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="StartChoice" apiName="StartChoice" russianName="НачалоВыбора"/>
              <Event name="StartListChoice" apiName="StartListChoice" russianName="НачалоВыбораИзСписка"/>
              <Event name="ChoiceProcessing" apiName="ChoiceProcessing" russianName="ОбработкаВыбора"/>
              <Event name="Opening" apiName="Opening" russianName="Открытие"/>
              <Event name="Clearing" apiName="Clearing" russianName="Очистка"/>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
              <Event name="Tuning" apiName="Tuning" russianName="Регулирование"/>
            </Events>
          </Control>
          <Control name="RadioButton" apiName="RadioButton" russianName="Переключатель" children="none">
            <Properties>
              <Property name="VerticalAlign" apiName="VerticalAlign" russianName="ВертикальноеПоложение" russianType="ВертикальноеПоложение" valueCodec="enumeration"/>
              <Property name="SelectionValue" apiName="SelectionValue" russianName="ВыбираемоеЗначение" russianType="Совпадает с описанием типа первого в группе переключателя" valueCodec="unclassified"/>
              <Property name="HorizontalAlign" apiName="HorizontalAlign" russianName="ГоризонтальноеПоложение" russianType="ГоризонтальноеПоложение" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="FirstInGroup" apiName="FirstInGroup" russianName="ПервыйВГруппе" russianType="Булево" valueCodec="boolean"/>
              <Property name="TitleLocation" apiName="TitleLocation" russianName="ПоложениеЗаголовка" russianType="ПоложениеЗаголовка" valueCodec="enumeration"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
            </Events>
          </Control>
          <Control name="InputField" apiName="TextBox" russianName="ПолеВвода" children="none">
            <Properties>
              <Property name="AutoChoiceIncomplete" apiName="AutoChoiceIncomplete" russianName="АвтоВыборНезаполненного" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoMarkIncomplete" apiName="AutoMarkIncomplete" russianName="АвтоОтметкаНезаполненного" russianType="Булево" valueCodec="boolean"/>
              <Property name="Wrap" apiName="Wrap" russianName="АвтоПереносСтрок" russianType="Булево" valueCodec="boolean"/>
              <Property name="VerticalAlign" apiName="VerticalAlign" russianName="ВертикальноеПоложение" russianType="ВертикальноеПоложение" valueCodec="enumeration"/>
              <Property name="ChooseType" apiName="ChooseType" russianName="ВыбиратьТип" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChoiceIncomplete" apiName="ChoiceIncomplete" russianName="ВыборНезаполненного" russianType="Булево" valueCodec="boolean"/>
              <Property name="SelectedText" apiName="SelectedText" russianName="ВыделенныйТекст" russianType="Строка" valueCodec="string"/>
              <Property name="MarkNegatives" apiName="MarkNegatives" russianName="ВыделятьОтрицательные" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChoiceListHeight" apiName="ChoiceListHeight" russianName="ВысотаСпискаВыбора" russianType="Число" valueCodec="decimal"/>
              <Property name="HorizontalAlign" apiName="HorizontalAlign" russianName="ГоризонтальноеПоложение" russianType="ГоризонтальноеПоложение" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="SelButtonPicture" apiName="SelButtonPicture" russianName="КартинкаКнопкиВыбора" russianType="Картинка" valueCodec="picture"/>
              <Property name="ChoiceButtonPicture" apiName="ChoiceButtonPicture" russianName="КартинкаКнопкиВыбора" russianType="Картинка" valueCodec="picture"/>
              <Property name="ChoiceButton" apiName="ChoiceButton" russianName="КнопкаВыбора" russianType="Булево" valueCodec="boolean"/>
              <Property name="OpenButton" apiName="OpenButton" russianName="КнопкаОткрытия" russianType="Булево" valueCodec="boolean"/>
              <Property name="ClearButton" apiName="ClearButton" russianName="КнопкаОчистки" russianType="Булево" valueCodec="boolean"/>
              <Property name="SpinButton" apiName="SpinButton" russianName="КнопкаРегулирования" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChoiceListButton" apiName="ChoiceListButton" russianName="КнопкаСпискаВыбора" russianType="Булево" valueCodec="boolean"/>
              <Property name="MaxValue" apiName="MaxValue" russianName="МаксимальноеЗначение" russianType="Произвольный" valueCodec="unclassified"/>
              <Property name="Mask" apiName="Mask" russianName="Маска" russianType="Строка" valueCodec="string"/>
              <Property name="MinValue" apiName="MinValue" russianName="МинимальноеЗначение" russianType="Произвольный" valueCodec="unclassified"/>
              <Property name="MultiLine" apiName="MultiLine" russianName="МногострочныйРежим" russianType="Булево" valueCodec="boolean"/>
              <Property name="TypeRestriction" apiName="TypeRestriction" russianName="ОграничениеТипа" russianType="ОписаниеТипов" valueCodec="type-domain"/>
              <Property name="MarkIncomplete" apiName="MarkIncomplete" russianName="ОтметкаНезаполненного" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="ExtendedEdit" apiName="ExtendedEdit" russianName="РасширенноеРедактирование" russianType="Булево" valueCodec="boolean"/>
              <Property name="TextEdit" apiName="TextEdit" russianName="РедактированиеТекста" russianType="Булево" valueCodec="boolean"/>
              <Property name="ListChoiceMode" apiName="ListChoiceMode" russianName="РежимВыбораИзСписка" russianType="Булево" valueCodec="boolean"/>
              <Property name="IncompleteChoiceMode" apiName="IncompleteChoiceMode" russianName="РежимВыбораНезаполненного" russianType="РежимВыбораНезаполненного" valueCodec="enumeration"/>
              <Property name="PasswordMode" apiName="PasswordMode" russianName="РежимПароля" russianType="Булево" valueCodec="boolean"/>
              <Property name="Shortcut" apiName="Shortcut" russianName="СочетаниеКлавиш" russianType="СочетаниеКлавиш" valueCodec="unclassified"/>
              <Property name="ChoiceList" apiName="ChoiceList" russianName="СписокВыбора" russianType="СписокЗначений" valueCodec="unclassified"/>
              <Property name="ReadOnly" apiName="ReadOnly" russianName="ТолькоПросмотр" russianType="Булево" valueCodec="boolean"/>
              <Property name="Format" apiName="Format" russianName="Формат" russianType="Строка" valueCodec="string"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonTextColor" apiName="ButtonTextColor" russianName="ЦветТекстаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="ChoiceListWidth" apiName="ChoiceListWidth" russianName="ШиринаСпискаВыбора" russianType="Число" valueCodec="decimal"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
              <Property name="TypeLinkItem" apiName="TypeLinkItem" russianName="ЭлементСвязиПоТипу" russianType="" valueCodec="unclassified"/>
            </Properties>
            <Events>
              <Event name="AutoCompleteText" apiName="AutoCompleteText" russianName="АвтоПодборТекста"/>
              <Event name="StartChoice" apiName="StartChoice" russianName="НачалоВыбора"/>
              <Event name="StartListChoice" apiName="StartListChoice" russianName="НачалоВыбораИзСписка"/>
              <Event name="ChoiceProcessing" apiName="ChoiceProcessing" russianName="ОбработкаВыбора"/>
              <Event name="TextEditEnd" apiName="TextEditEnd" russianName="ОкончаниеВводаТекста"/>
              <Event name="Opening" apiName="Opening" russianName="Открытие"/>
              <Event name="Clearing" apiName="Clearing" russianName="Очистка"/>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
              <Event name="Tuning" apiName="Tuning" russianName="Регулирование"/>
            </Events>
          </Control>
          <Control name="UsualGroup" apiName="GroupBox" russianName="РамкаГруппы" children="controls">
            <Properties>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
            </Events>
          </Control>
          <Control name="Splitter" apiName="Splitter" russianName="Разделитель" children="none">
            <Properties>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Orientation" apiName="Orientation" russianName="Ориентация" russianType="Ориентация" valueCodec="enumeration"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
            </Events>
          </Control>
          <Control name="Chart" apiName="Chart" russianName="Диаграмма" children="none">
            <Properties>
              <Property name="AutoMaxValue" apiName="AutoMaxValue" russianName="АвтоМаксимальноеЗначение" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoMinValue" apiName="AutoMinValue" russianName="АвтоМинимальноеЗначение" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoSeriesSeparation" apiName="AutoSeriesSeparation" russianName="АвтоРаздвижениеСерий" russianType="АвтоРаздвижениеСерий" valueCodec="enumeration"/>
              <Property name="AutoTransposition" apiName="AutoTransposition" russianName="АвтоТранспонирование" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoSeriesText" apiName="AutoSeriesText" russianName="АвтоУстановкаТекстаСерий" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoPointText" apiName="AutoPointText" russianName="АвтоУстановкаТекстаТочек" russianType="Булево" valueCodec="boolean"/>
              <Property name="ActiveSeries" apiName="ActiveSeries" russianName="АктивнаяСерия" russianType="СерияДиаграммы" valueCodec="unclassified"/>
              <Property name="ActivePoint" apiName="ActivePoint" russianName="АктивнаяТочка" russianType="ТочкаДиаграммы" valueCodec="unclassified"/>
              <Property name="BaseValue" apiName="BaseValue" russianName="БазовоеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="LabelType" apiName="LabelType" russianName="ВидПодписей" russianType="ВидПодписейКДиаграмме" valueCodec="enumeration"/>
              <Property name="Gradient" apiName="Gradient" russianName="Градиент" russianType="Булево" valueCodec="boolean"/>
              <Property name="DataSource" apiName="DataSource" russianName="ИсточникДанных" russianType="ТаблицаЗначений ; ОбластьЯчеекТабличногоДокумента" valueCodec="unclassified"/>
              <Property name="SeriesCount" apiName="SeriesCount" russianName="КоличествоСерий" russianType="Число" valueCodec="decimal"/>
              <Property name="PointCount" apiName="PointCount" russianName="КоличествоТочек" russianType="Число" valueCodec="decimal"/>
              <Property name="EndGaugeAngle" apiName="EndGaugeAngle" russianName="КонечныйУголИзмерительнойДиаграммы" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxValue" apiName="MaxValue" russianName="МаксимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxSeries" apiName="MaxSeries" russianName="МаксимумСерий" russianType="МаксимумСерий" valueCodec="enumeration"/>
              <Property name="MaxSeriesCount" apiName="MaxSeriesCount" russianName="МаксимумСерийКоличество" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxSeriesPercent" apiName="MaxSeriesPercent" russianName="МаксимумСерийПроцент" russianType="Число" valueCodec="decimal"/>
              <Property name="MinValue" apiName="MinValue" russianName="МинимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="BeginGaugeAngle" apiName="BeginGaugeAngle" russianName="НачальныйУголИзмерительнойДиаграммы" russianType="Число" valueCodec="decimal"/>
              <Property name="TitleArea" apiName="TitleArea" russianName="ОбластьЗаголовка" russianType="ОбластьЗаголовкаДиаграммы" valueCodec="unclassified"/>
              <Property name="LegendArea" apiName="LegendArea" russianName="ОбластьЛегенды" russianType="ОбластьЛегендыДиаграммы" valueCodec="unclassified"/>
              <Property name="PlotArea" apiName="PlotArea" russianName="ОбластьПостроения" russianType="ОбластьПостроенияДиаграммы" valueCodec="unclassified"/>
              <Property name="RefreshEnabled" apiName="RefreshEnabled" russianName="Обновление" russianType="Булево" valueCodec="boolean"/>
              <Property name="Outline" apiName="Outline" russianName="Окантовка" russianType="Булево" valueCodec="boolean"/>
              <Property name="Orientation" apiName="Orientation" russianName="Ориентация" russianType="ОриентацияДиаграммы" valueCodec="enumeration"/>
              <Property name="ShowTitle" apiName="ShowTitle" russianName="ОтображатьЗаголовок" russianType="Булево" valueCodec="boolean"/>
              <Property name="ShowLegend" apiName="ShowLegend" russianName="ОтображатьЛегенду" russianType="Булево" valueCodec="boolean"/>
              <Property name="GaugeChartValueRepresentation" apiName="GaugeChartValueRepresentation" russianName="ОтображениеЗначенияИзмерительнойДиаграммы" russianType="ОтображениеЗначенияИзмерительнойДиаграммы" valueCodec="enumeration"/>
              <Property name="ColorPalette" apiName="ColorPalette" russianName="ПалитраЦветов" russianType="ПалитраЦветовДиаграммы" valueCodec="enumeration"/>
              <Property name="GaugeChartValuesScaleLabelsArcDirection" apiName="GaugeChartValuesScaleLabelsArcDirection" russianName="ПодписиШкалыЗначенийИзмерительнойДиаграммыВдольШкалы" russianType="Булево" valueCodec="boolean"/>
              <Property name="LabelLocation" apiName="LabelLocation" russianName="ПоложениеПодписей" russianType="ПоложениеПодписейКДиаграмме" valueCodec="enumeration"/>
              <Property name="GaugeChartValuesScaleLabelsLocation" apiName="GaugeChartValuesScaleLabelsLocation" russianName="ПоложениеПодписейШкалыЗначенийИзмерительнойДиаграммы" russianType="ПоложениеПодписейШкалыЗначенийИзмерительнойДиаграммы" valueCodec="enumeration"/>
              <Property name="GaugeChartQualityBands" apiName="GaugeChartQualityBands" russianName="ПолосыИзмерительнойДиаграммы" russianType="ПолосыИзмерительнойДиаграммы" valueCodec="unclassified"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="TransparentLabel" apiName="TransparentLabel" russianName="ПрозрачныйФонПодписей" russianType="Булево" valueCodec="boolean"/>
              <Property name="HideBaseValue" apiName="HideBaseValue" russianName="ПропускатьБазовоеЗначение" russianType="Булево" valueCodec="boolean"/>
              <Property name="LabelDelimiter" apiName="LabelDelimiter" russianName="РазделительПодписей" russianType="Строка" valueCodec="string"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="LabelBorder" apiName="LabelBorder" russianName="РамкаПодписей" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="SpaceMode" apiName="SpaceMode" russianName="РежимПробелов" russianType="РежимПробеловДиаграммы" valueCodec="enumeration"/>
              <Property name="Light" apiName="Light" russianName="Свет" russianType="Булево" valueCodec="boolean"/>
              <Property name="SummarySeries" apiName="SummarySeries" russianName="СводнаяСерия" russianType="СерияДиаграммы" valueCodec="unclassified"/>
              <Property name="Series" apiName="Series" russianName="Серии" russianType="СерииДиаграммы" valueCodec="unclassified"/>
              <Property name="SeriesInRows" apiName="SeriesInRows" russianName="СерииВСтроках" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChartType" apiName="ChartType" russianName="ТипДиаграммы" russianType="ТипДиаграммы" valueCodec="enumeration"/>
              <Property name="GaugeBushThickness" apiName="GaugeBushThickness" russianName="ТолщинаВтулкиИзмерительнойДиаграммы" russianType="Число" valueCodec="decimal"/>
              <Property name="GaugeThickness" apiName="GaugeThickness" russianName="ТолщинаШкалыИзмерительнойДиаграммы" russianType="Число" valueCodec="decimal"/>
              <Property name="Points" apiName="Points" russianName="Точки" russianType="ТочкиДиаграммы" valueCodec="unclassified"/>
              <Property name="ValueLabelFormat" apiName="ValueLabelFormat" russianName="ФорматЗначенийВПодписях" russianType="Строка" valueCodec="string"/>
              <Property name="PercentLabelFormat" apiName="PercentLabelFormat" russianName="ФорматПроцентовВПодписях" russianType="Строка" valueCodec="string"/>
              <Property name="GaugeBushColor" apiName="GaugeBushColor" russianName="ЦветВтулкиИзмерительнойДиаграммы" russianType="Цвет" valueCodec="color"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="LabelBorderColor" apiName="LabelBorderColor" russianName="ЦветРамкиПодписей" russianType="Цвет" valueCodec="color"/>
              <Property name="LabelTextColor" apiName="LabelTextColor" russianName="ЦветТекстаПодписей" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="LabelBackColor" apiName="LabelBackColor" russianName="ЦветФонаПодписей" russianType="Цвет" valueCodec="color"/>
              <Property name="LabelFont" apiName="LabelFont" russianName="ШрифтПодписей" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="DetailProcessing" apiName="DetailProcessing" russianName="ОбработкаРасшифровки"/>
            </Events>
          </Control>
          <Control name="PivotChart" apiName="PivotChart" russianName="СводнаяДиаграмма" children="none">
            <Properties>
              <Property name="DataSource" apiName="DataSource" russianName="ИсточникДанных" russianType="РезультатЗапроса ; ПостроительОтчета" valueCodec="unclassified"/>
              <Property name="Fields" apiName="Fields" russianName="Поля" russianType="КоллекцияПолейСводнойДиаграммы" valueCodec="unclassified"/>
              <Property name="PivotChartType" apiName="PivotChartType" russianName="ТипСводнойДиаграммы" russianType="ТипСводнойДиаграммы" valueCodec="enumeration"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="DetailProcessing" apiName="DetailProcessing" russianName="ОбработкаРасшифровки"/>
            </Events>
          </Control>
          <Control name="GanttChart" apiName="GanttChart" russianName="ДиаграммаГанта" children="none">
            <Properties>
              <Property name="AutoMaxWidth" apiName="AutoMaxWidth" russianName="АвтоМаксимальнаяШирина" russianType="Булево" valueCodec="boolean"/>
              <Property name="PeriodicVariantUnit" apiName="PeriodicVariantUnit" russianName="ЕдиницаПериодическогоВарианта" russianType="ТипЕдиницыШкалыВремени" valueCodec="enumeration"/>
              <Property name="PeriodicVariantRepetition" apiName="PeriodicVariantRepetition" russianName="КратностьПериодическогоВарианта" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxWidth" apiName="MaxWidth" russianName="МаксимальнаяШирина" russianType="Число" valueCodec="decimal"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="OnIntervalEditEnd" apiName="OnIntervalEditEnd" russianName="ПриОкончанииРедактированияИнтервала"/>
            </Events>
          </Control>
          <Control name="Dendrogram" apiName="Dendrogram" russianName="Дендрограмма" children="none">
            <Properties>
              <Property name="AutoMaxHeight" apiName="AutoMaxHeight" russianName="АвтоМаксимальнаяВысота" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoMaxWidth" apiName="AutoMaxWidth" russianName="АвтоМаксимальнаяШирина" russianType="Булево" valueCodec="boolean"/>
              <Property name="Height" apiName="Height" russianName="Высота" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxHeight" apiName="MaxHeight" russianName="МаксимальнаяВысота" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxWidth" apiName="MaxWidth" russianName="МаксимальнаяШирина" russianType="Число" valueCodec="decimal"/>
              <Property name="VerticalStretch" apiName="VerticalStretch" russianName="РастягиватьПоВертикали" russianType="Булево" valueCodec="boolean"/>
              <Property name="HorizontalStretch" apiName="HorizontalStretch" russianName="РастягиватьПоГоризонтали" russianType="Булево" valueCodec="boolean"/>
              <Property name="Width" apiName="Width" russianName="Ширина" russianType="Число" valueCodec="decimal"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="DetailProcessing" apiName="DetailProcessing" russianName="ОбработкаРасшифровки"/>
            </Events>
          </Control>
          <Control name="HTMLDocumentField" apiName="HTMLDocumentField" russianName="ПолеHTMLДокумента" children="none">
            <Properties>
              <Property name="Output" apiName="Output" russianName="Вывод" russianType="ИспользованиеВывода" valueCodec="enumeration"/>
              <Property name="Document" apiName="Document" russianName="Документ" russianType="COMОбъект" valueCodec="unclassified"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="DocumentComplete" apiName="DocumentComplete" russianName="ДокументСформирован"/>
            </Events>
          </Control>
          <Control name="ListBox" apiName="ListBox" russianName="ПолеСписка" children="none">
            <Properties>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="ShowPicture" apiName="ShowPicture" russianName="ОтображатьКартинку" russianType="Булево" valueCodec="boolean"/>
              <Property name="ShowCheckBox" apiName="ShowCheckBox" russianName="ОтображатьПометку" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="CurrentRow" apiName="CurrentRow" russianName="ТекущаяСтрока" russianType="ЭлементСпискаЗначений" valueCodec="unclassified"/>
              <Property name="ReadOnly" apiName="ReadOnly" russianName="ТолькоПросмотр" russianType="Булево" valueCodec="boolean"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="OnActivateRow" apiName="OnActivateRow" russianName="ПриАктивизацииСтроки"/>
              <Event name="OnCheckChange" apiName="OnCheckChange" russianName="ПриИзмененииФлажка"/>
            </Events>
          </Control>
          <Control name="ProgressBar" apiName="ProgressBar" russianName="Индикатор" children="none">
            <Properties>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="MaxValue" apiName="MaxValue" russianName="МаксимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="MinValue" apiName="MinValue" russianName="МинимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="Orientation" apiName="Orientation" russianName="Ориентация" russianType="Ориентация" valueCodec="enumeration"/>
              <Property name="ShowPercent" apiName="ShowPercent" russianName="ОтображатьПроценты" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="ShowStyle" apiName="ShowStyle" russianName="СтильОтображения" russianType="РежимСглаживанияИндикатора" valueCodec="enumeration"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="Step" apiName="Step" russianName="Шаг" russianType="Число" valueCodec="decimal"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
            </Events>
          </Control>
          <Control name="TrackBar" apiName="TrackBar" russianName="ПолосаРегулирования" children="none">
            <Properties>
              <Property name="LargeStep" apiName="LargeStep" russianName="БольшойШаг" russianType="Число" valueCodec="decimal"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="MaxValue" apiName="MaxValue" russianName="МаксимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="MinValue" apiName="MinValue" russianName="МинимальноеЗначение" russianType="Число" valueCodec="decimal"/>
              <Property name="Orientation" apiName="Orientation" russianName="Ориентация" russianType="Ориентация" valueCodec="enumeration"/>
              <Property name="MarkingAppearance" apiName="MarkingAppearance" russianName="ОтображениеРазметки" russianType="ОтображениеРазметкиПолосыРегулирования" valueCodec="enumeration"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="Step" apiName="Step" russianName="Шаг" russianType="Число" valueCodec="decimal"/>
              <Property name="MarkingStep" apiName="MarkingStep" russianName="ШагРазметки" russianType="Число" valueCodec="decimal"/>
            </Properties>
            <Events>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
            </Events>
          </Control>
          <Control name="CalendarField" apiName="CalendarBox" russianName="ПолеКалендаря" children="none">
            <Properties>
              <Property name="SelectedDates" apiName="SelectedDates" russianName="ВыделенныеДаты" russianType="КоллекцияВыделенныхДат" valueCodec="unclassified"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="EndOfDisplayPeriod" apiName="EndOfDisplayPeriod" russianName="КонецПериодаОтображения" russianType="Дата ; Неопределено" valueCodec="date"/>
              <Property name="BeginOfDisplayPeriod" apiName="BeginOfDisplayPeriod" russianName="НачалоПериодаОтображения" russianType="Дата ; Неопределено" valueCodec="date"/>
              <Property name="ShowCurrentDate" apiName="ShowCurrentDate" russianName="ОтображатьТекущуюДату" russianType="Булево" valueCodec="boolean"/>
              <Property name="CalendarNavigation" apiName="CalendarNavigation" russianName="ПеремещениеПоКалендарю" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="EnableStartDrag" apiName="EnableStartDrag" russianName="РазрешитьНачалоПеретаскивания" russianType="Булево" valueCodec="boolean"/>
              <Property name="EnableDrag" apiName="EnableDrag" russianName="РазрешитьПеретаскивание" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="SelectionMode" apiName="SelectionMode" russianName="РежимВыделения" russianType="РежимВыделенияДаты" valueCodec="enumeration"/>
              <Property name="CurrentDate" apiName="CurrentDate" russianName="ТекущаяДата" russianType="Дата" valueCodec="date"/>
              <Property name="HolidayColor" apiName="HolidayColor" russianName="ЦветВыходныхДней" russianType="Цвет" valueCodec="color"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="SelectionTextColor" apiName="SelectionTextColor" russianName="ЦветТекстаВыделения" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonTextColor" apiName="ButtonTextColor" russianName="ЦветТекстаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldTextColor" apiName="FieldTextColor" russianName="ЦветТекстаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="SelectionBackColor" apiName="SelectionBackColor" russianName="ЦветФонаВыделения" russianType="Цвет" valueCodec="color"/>
              <Property name="ButtonBackColor" apiName="ButtonBackColor" russianName="ЦветФонаКнопки" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="DragStart" apiName="DragStart" russianName="НачалоПеретаскивания"/>
              <Event name="DragEnd" apiName="DragEnd" russianName="ОкончаниеПеретаскивания"/>
              <Event name="Drag" apiName="Drag" russianName="Перетаскивание"/>
              <Event name="OnActivateDate" apiName="OnActivateDate" russianName="ПриАктивизацииДаты"/>
              <Event name="OnPeriodOutput" apiName="OnPeriodOutput" russianName="ПриВыводеПериода"/>
              <Event name="OnChange" apiName="OnChange" russianName="ПриИзменении"/>
              <Event name="DragCheck" apiName="DragCheck" russianName="ПроверкаПеретаскивания"/>
            </Events>
          </Control>
          <Control name="TextDocumentField" apiName="TextDocumentField" russianName="ПолеТекстовогоДокумента" children="none">
            <Properties>
              <Property name="SelectedText" apiName="SelectedText" russianName="ВыделенныйТекст" russianType="Строка" valueCodec="string"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
            </Events>
          </Control>
          <Control name="GeographicalSchemaField" apiName="GeographicalSchemaField" russianName="ПолеГеографическойСхемы" children="none">
            <Properties>
              <Property name="AutoMaxHeight" apiName="AutoMaxHeight" russianName="АвтоМаксимальнаяВысота" russianType="Булево" valueCodec="boolean"/>
              <Property name="AutoMaxWidth" apiName="AutoMaxWidth" russianName="АвтоМаксимальнаяШирина" russianType="Булево" valueCodec="boolean"/>
              <Property name="Height" apiName="Height" russianName="Высота" russianType="Число" valueCodec="decimal"/>
              <Property name="Output" apiName="Output" russianName="Вывод" russianType="ИспользованиеВывода" valueCodec="enumeration"/>
              <Property name="MaxHeight" apiName="MaxHeight" russianName="МаксимальнаяВысота" russianType="Число" valueCodec="decimal"/>
              <Property name="MaxWidth" apiName="MaxWidth" russianName="МаксимальнаяШирина" russianType="Число" valueCodec="decimal"/>
              <Property name="Scale" apiName="Scale" russianName="Масштаб" russianType="Число" valueCodec="decimal"/>
              <Property name="ShowedArea" apiName="ShowedArea" russianName="ОтображаемаяОбласть" russianType="ПоказываемаяОбластьГеографическойСхемы" valueCodec="unclassified"/>
              <Property name="ScaleKeeping" apiName="ScaleKeeping" russianName="ПоддержкаМасштаба" russianType="РежимОтображенияГеографическойСхемы" valueCodec="enumeration"/>
              <Property name="VerticalStretch" apiName="VerticalStretch" russianName="РастягиватьПоВертикали" russianType="Булево" valueCodec="boolean"/>
              <Property name="HorizontalStretch" apiName="HorizontalStretch" russianName="РастягиватьПоГоризонтали" russianType="Булево" valueCodec="boolean"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="Width" apiName="Width" russianName="Ширина" russianType="Число" valueCodec="decimal"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
            </Events>
          </Control>
          <Control name="GraphicalSchemaField" apiName="GraphicalSchemaField" russianName="ПолеГрафическойСхемы" children="none">
            <Properties>
              <Property name="Height" apiName="Height" russianName="Высота" russianType="Число" valueCodec="decimal"/>
              <Property name="Output" apiName="Output" russianName="Вывод" russianType="ИспользованиеВывода" valueCodec="enumeration"/>
              <Property name="Edit" apiName="Edit" russianName="Редактирование" russianType="Булево" valueCodec="boolean"/>
              <Property name="VerticalStretch" apiName="VerticalStretch" russianName="РастягиватьПоВертикали" russianType="Булево" valueCodec="boolean"/>
              <Property name="HorizontalStretch" apiName="HorizontalStretch" russianName="РастягиватьПоГоризонтали" russianType="Булево" valueCodec="boolean"/>
              <Property name="CurrentItem" apiName="CurrentItem" russianName="ТекущийЭлемент" russianType="ЭлементГрафическойСхемы" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="Width" apiName="Width" russianName="Ширина" russianType="Число" valueCodec="decimal"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="OnActivate" apiName="OnActivate" russianName="ПриАктивизации"/>
            </Events>
          </Control>
          <Control name="Table" apiName="TableBox" russianName="ТабличноеПоле" children="none">
            <Properties>
              <Property name="AutoInsertNewRow" apiName="AutoInsertNewRow" russianName="АвтоВводНовойСтроки" russianType="Булево" valueCodec="boolean"/>
              <Property name="VerticalScrollBar" apiName="VerticalScrollBar" russianName="ВертикальнаяПолосаПрокрутки" russianType="ИспользованиеПолосыПрокрутки" valueCodec="enumeration"/>
              <Property name="VerticalLines" apiName="VerticalLines" russianName="ВертикальныеЛинии" russianType="Булево" valueCodec="boolean"/>
              <Property name="Output" apiName="Output" russianName="Вывод" russianType="ИспользованиеВывода" valueCodec="enumeration"/>
              <Property name="SelectedRows" apiName="SelectedRows" russianName="ВыделенныеСтроки" russianType="ВыделенныеСтрокиТабличногоПоля" valueCodec="unclassified"/>
              <Property name="FooterHeight" apiName="FooterHeight" russianName="ВысотаПодвала" russianType="Число" valueCodec="decimal"/>
              <Property name="HeaderHeight" apiName="HeaderHeight" russianName="ВысотаШапки" russianType="Число" valueCodec="decimal"/>
              <Property name="HorizontalScrollBar" apiName="HorizontalScrollBar" russianName="ГоризонтальнаяПолосаПрокрутки" russianType="ИспользованиеПолосыПрокрутки" valueCodec="enumeration"/>
              <Property name="HorizontalLines" apiName="HorizontalLines" russianName="ГоризонтальныеЛинии" russianType="Булево" valueCodec="boolean"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChangeSettingOfColumns" apiName="ChangeSettingOfColumns" russianName="ИзменятьНастройкуКолонок" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChangePositionOfColumns" apiName="ChangePositionOfColumns" russianName="ИзменятьПозициюКолонок" russianType="Булево" valueCodec="boolean"/>
              <Property name="ChangeRowSet" apiName="ChangeRowSet" russianName="ИзменятьСоставСтрок" russianType="Булево" valueCodec="boolean"/>
              <Property name="Columns" apiName="Columns" russianName="Колонки" russianType="КолонкиТабличногоПоля" valueCodec="unclassified"/>
              <Property name="InitialTreeView" apiName="InitialTreeView" russianName="НачальноеОтображениеДерева" russianType="НачальноеОтображениеДерева" valueCodec="enumeration"/>
              <Property name="InitialListView" apiName="InitialListView" russianName="НачальноеОтображениеСписка" russianType="НачальноеОтображениеСписка" valueCodec="enumeration"/>
              <Property name="Footer" apiName="Footer" russianName="Подвал" russianType="Булево" valueCodec="boolean"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="EnableStartDrag" apiName="EnableStartDrag" russianName="РазрешитьНачалоПеретаскивания" russianType="Булево" valueCodec="boolean"/>
              <Property name="EnableDrag" apiName="EnableDrag" russianName="РазрешитьПеретаскивание" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="RowInputMode" apiName="RowInputMode" russianName="РежимВводаСтрок" russianType="РежимВводаСтрокТабличногоПоля" valueCodec="enumeration"/>
              <Property name="ChoiceMode" apiName="ChoiceMode" russianName="РежимВыбора" russianType="Булево" valueCodec="boolean"/>
              <Property name="SelectionMode" apiName="SelectionMode" russianName="РежимВыделения" russianType="РежимВыделенияТабличногоПоля" valueCodec="enumeration"/>
              <Property name="RowSelectionMode" apiName="RowSelectionMode" russianName="РежимВыделенияСтроки" russianType="РежимВыделенияСтрокиТабличногоПоля" valueCodec="enumeration"/>
              <Property name="CurrentColumn" apiName="CurrentColumn" russianName="ТекущаяКолонка" russianType="КолонкаТабличногоПоля" valueCodec="unclassified"/>
              <Property name="CurrentRow" apiName="CurrentRow" russianName="ТекущаяСтрока" russianType="" valueCodec="unclassified"/>
              <Property name="CurrentData" apiName="CurrentData" russianName="ТекущиеДанные" russianType="" valueCodec="unclassified"/>
              <Property name="CurrentParent" apiName="CurrentParent" russianName="ТекущийРодитель" russianType="" valueCodec="unclassified"/>
              <Property name="ReadOnly" apiName="ReadOnly" russianName="ТолькоПросмотр" russianType="Булево" valueCodec="boolean"/>
              <Property name="FixedLeft" apiName="FixedLeft" russianName="ФиксацияСлева" russianType="Число" valueCodec="decimal"/>
              <Property name="FixedRight" apiName="FixedRight" russianName="ФиксацияСправа" russianType="Число" valueCodec="decimal"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="SelectionTextColor" apiName="SelectionTextColor" russianName="ЦветТекстаВыделения" russianType="Цвет" valueCodec="color"/>
              <Property name="FooterTextColor" apiName="FooterTextColor" russianName="ЦветТекстаПодвала" russianType="Цвет" valueCodec="color"/>
              <Property name="HeaderTextColor" apiName="HeaderTextColor" russianName="ЦветТекстаШапки" russianType="Цвет" valueCodec="color"/>
              <Property name="SelectionBackColor" apiName="SelectionBackColor" russianName="ЦветФонаВыделения" russianType="Цвет" valueCodec="color"/>
              <Property name="FooterBackColor" apiName="FooterBackColor" russianName="ЦветФонаПодвала" russianType="Цвет" valueCodec="color"/>
              <Property name="FieldBackColor" apiName="FieldBackColor" russianName="ЦветФонаПоля" russianType="Цвет" valueCodec="color"/>
              <Property name="AlternationRowBackColor" apiName="AlternationRowBackColor" russianName="ЦветФонаЧередованияСтрок" russianType="Цвет" valueCodec="color"/>
              <Property name="HeaderBackColor" apiName="HeaderBackColor" russianName="ЦветФонаШапки" russianType="Цвет" valueCodec="color"/>
              <Property name="UseAlternationRowColor" apiName="UseAlternationRowColor" russianName="ЧередованиеЦветовСтрок" russianType="Булево" valueCodec="boolean"/>
              <Property name="Header" apiName="Header" russianName="Шапка" russianType="Булево" valueCodec="boolean"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
              <Property name="FooterFont" apiName="FooterFont" russianName="ШрифтПодвала" russianType="Шрифт" valueCodec="font"/>
              <Property name="HeaderFont" apiName="HeaderFont" russianName="ШрифтШапки" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="ValueChoice" apiName="ValueChoice" russianName="ВыборЗначения"/>
              <Event name="DragStart" apiName="DragStart" russianName="НачалоПеретаскивания"/>
              <Event name="ChoiceProcessing" apiName="ChoiceProcessing" russianName="ОбработкаВыбора"/>
              <Event name="NewObjectWriteProcessing" apiName="NewObjectWriteProcessing" russianName="ОбработкаЗаписиНовогоОбъекта"/>
              <Event name="DragEnd" apiName="DragEnd" russianName="ОкончаниеПеретаскивания"/>
              <Event name="BeforeAddRow" apiName="BeforeAddRow" russianName="ПередНачаломДобавления"/>
              <Event name="BeforeRowChange" apiName="BeforeRowChange" russianName="ПередНачаломИзменения"/>
              <Event name="BeforeEditEnd" apiName="BeforeEditEnd" russianName="ПередОкончаниемРедактирования"/>
              <Event name="BeforeDeleteRow" apiName="BeforeDeleteRow" russianName="ПередУдалением"/>
              <Event name="Drag" apiName="Drag" russianName="Перетаскивание"/>
              <Event name="AfterDeleteLine" apiName="AfterDeleteLine" russianName="ПослеУдаления"/>
              <Event name="OnActivateColumn" apiName="OnActivateColumn" russianName="ПриАктивизацииКолонки"/>
              <Event name="OnActivateRow" apiName="OnActivateRow" russianName="ПриАктивизацииСтроки"/>
              <Event name="OnActivateCell" apiName="OnActivateCell" russianName="ПриАктивизацииЯчейки"/>
              <Event name="OnRowOutput" apiName="OnRowOutput" russianName="ПриВыводеСтроки"/>
              <Event name="OnCheckChange" apiName="OnCheckChange" russianName="ПриИзмененииФлажка"/>
              <Event name="OnStartEdit" apiName="OnStartEdit" russianName="ПриНачалеРедактирования"/>
              <Event name="OnEditEnd" apiName="OnEditEnd" russianName="ПриОкончанииРедактирования"/>
              <Event name="OnDataGet" apiName="OnDataGet" russianName="ПриПолученииДанных"/>
              <Event name="OnCurrentParentChange" apiName="OnCurrentParentChange" russianName="ПриСменеТекущегоРодителя"/>
              <Event name="DragCheck" apiName="DragCheck" russianName="ПроверкаПеретаскивания"/>
            </Events>
          </Control>
          <Control name="SpreadsheetDocumentField" apiName="SpreadsheetDocumentField" russianName="ПолеТабличногоДокумента" children="none">
            <Properties>
              <Property name="VerticalScrollBar" apiName="VerticalScrollBar" russianName="ВертикальнаяПолосаПрокрутки" russianType="Булево" valueCodec="boolean"/>
              <Property name="HorizontalScrollBar" apiName="HorizontalScrollBar" russianName="ГоризонтальнаяПолосаПрокрутки" russianType="Булево" valueCodec="boolean"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="ShowSelection" apiName="ShowSelection" russianName="ОтображатьВыделение" russianType="ТипОтображенияВыделенияТабличногоДокумента" valueCodec="enumeration"/>
              <Property name="EnableStartDrag" apiName="EnableStartDrag" russianName="РазрешитьНачалоПеретаскивания" russianType="Булево" valueCodec="boolean"/>
              <Property name="EnableDrag" apiName="EnableDrag" russianName="РазрешитьПеретаскивание" russianType="Булево" valueCodec="boolean"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
            </Properties>
            <Events>
              <Event name="Selection" apiName="Selection" russianName="Выбор"/>
              <Event name="DragStart" apiName="DragStart" russianName="НачалоПеретаскивания"/>
              <Event name="DetailProcessing" apiName="DetailProcessing" russianName="ОбработкаРасшифровки"/>
              <Event name="DragEnd" apiName="DragEnd" russianName="ОкончаниеПеретаскивания"/>
              <Event name="Drag" apiName="Drag" russianName="Перетаскивание"/>
              <Event name="OnActivateArea" apiName="OnActivateArea" russianName="ПриАктивизацииОбласти"/>
              <Event name="OnChangeAreaContent" apiName="OnChangeAreaContent" russianName="ПриИзмененииСодержимогоОбласти"/>
              <Event name="DragCheck" apiName="DragCheck" russianName="ПроверкаПеретаскивания"/>
            </Events>
          </Control>
          <Control name="LabelDecoration" apiName="Label" russianName="Надпись" children="none">
            <Properties>
              <Property name="ScrollingText" apiName="ScrollingText" russianName="БегущаяСтрока" russianType="РежимБегущейСтроки" valueCodec="enumeration"/>
              <Property name="VerticalAlign" apiName="VerticalAlign" russianName="ВертикальноеПоложение" russianType="ВертикальноеПоложение" valueCodec="enumeration"/>
              <Property name="MarkNegatives" apiName="MarkNegatives" russianName="ВыделятьОтрицательные" russianType="Булево" valueCodec="boolean"/>
              <Property name="Hyperlink" apiName="Hyperlink" russianName="Гиперссылка" russianType="Булево" valueCodec="boolean"/>
              <Property name="HorizontalAlign" apiName="HorizontalAlign" russianName="ГоризонтальноеПоложение" russianType="ГоризонтальноеПоложение" valueCodec="enumeration"/>
              <Property name="Enabled" apiName="Enabled" russianName="Доступность" russianType="Булево" valueCodec="boolean"/>
              <Property name="Caption" apiName="Caption" russianName="Заголовок" russianType="Строка" valueCodec="string"/>
              <Property name="Picture" apiName="Picture" russianName="Картинка" russianType="Картинка" valueCodec="picture"/>
              <Property name="ToolTip" apiName="ToolTip" russianName="Подсказка" russianType="Строка" valueCodec="string"/>
              <Property name="LabelPictureLocation" apiName="LabelPictureLocation" russianName="ПоложениеКартинкиНадписи" russianType="ПоложениеКартинкиНадписи" valueCodec="enumeration"/>
              <Property name="Transparent" apiName="Transparent" russianName="ПрозрачныйФон" russianType="Булево" valueCodec="boolean"/>
              <Property name="PictureSize" apiName="PictureSize" russianName="РазмерКартинки" russianType="РазмерКартинки" valueCodec="enumeration"/>
              <Property name="Border" apiName="Border" russianName="Рамка" russianType="Рамка" valueCodec="unclassified"/>
              <Property name="Shortcut" apiName="Shortcut" russianName="СочетаниеКлавиш" russianType="СочетаниеКлавиш" valueCodec="unclassified"/>
              <Property name="Format" apiName="Format" russianName="Формат" russianType="Строка" valueCodec="string"/>
              <Property name="BorderColor" apiName="BorderColor" russianName="ЦветРамки" russianType="Цвет" valueCodec="color"/>
              <Property name="TextColor" apiName="TextColor" russianName="ЦветТекста" russianType="Цвет" valueCodec="color"/>
              <Property name="BackColor" apiName="BackColor" russianName="ЦветФона" russianType="Цвет" valueCodec="color"/>
              <Property name="Font" apiName="Font" russianName="Шрифт" russianType="Шрифт" valueCodec="font"/>
            </Properties>
            <Events>
              <Event name="Click" apiName="Click" russianName="Нажатие"/>
            </Events>
          </Control>
          <Control name="ActiveXControl" apiName="ActiveXControl" russianName="ЭлементУправленияActiveX" children="none">
            <Properties>
              <Property name="CLSID" apiName="CLSID" russianName="CLSID" russianType="Идентификатор" valueCodec="uuid"/>
              <Property name="State" apiName="State" russianName="Состояние" russianType="ДвоичныеДанные" valueCodec="unclassified"/>
            </Properties>
            <Events>
            </Events>
          </Control>
        </Controls>
      </Palette>
    </xs:appinfo>
  </xs:annotation>
</xs:schema>
