"""Platform-to-public ordinary-form XML mapping tables.

The platform palette in ``OrdinaryFormPalette.xsd`` stores 1C Russian object,
property, and event names. Public ordinary ``Form.xml`` uses an English XML
vocabulary. This module is the explicit bridge between those two layers; it is
name mapping only, not proof that a property has a verified platform slot
writer.
"""

from __future__ import annotations


PLATFORM_PROPERTY_XML_NAME: dict[str, str] = {
    "CLSID": "Clsid",
    "АвтоВводНовойСтроки": "AutoInsertNewRow",
    "АвтоВыборНезаполненного": "AutoSelectIncomplete",
    "АвтоЗаполнение": "Autofill",
    "АвтоМаксимальнаяВысота": "AutoMaxHeight",
    "АвтоМаксимальнаяШирина": "AutoMaxWidth",
    "АвтоМаксимальноеЗначение": "AutoMaximumValue",
    "АвтоМинимальноеЗначение": "AutoMinimumValue",
    "АвтоОтметкаНезаполненного": "AutoMarkIncomplete",
    "АвтоПереносСтрок": "WordWrap",
    "АвтоПорядокОбхода": "AutoTraversalOrder",
    "АвтоРаздвижениеСерий": "AutoSeriesSpread",
    "АвтоТранспонирование": "AutoTranspose",
    "АвтоУстановкаТекстаСерий": "AutoSeriesText",
    "АвтоУстановкаТекстаТочек": "AutoPointText",
    "АктивнаяСерия": "ActiveSeries",
    "АктивнаяТочка": "ActivePoint",
    "БазовоеЗначение": "BaseValue",
    "БегущаяСтрока": "Marquee",
    "БольшойШаг": "BigStep",
    "ВертикальнаяПолосаПрокрутки": "VerticalScrollBar",
    "ВертикальноеПоложение": "VerticalAlign",
    "ВертикальныеЛинии": "VerticalLines",
    "ВидПодписей": "LabelsView",
    "Вспомогательная": "Auxiliary",
    "ВыбираемоеЗначение": "DataValue",
    "ВыбиратьТип": "TypeChoice",
    "ВыборНезаполненного": "IncompleteChoice",
    "Вывод": "Output",
    "ВыделенныеДаты": "SelectedDates",
    "ВыделенныеСтроки": "SelectedRows",
    "ВыделенныйТекст": "SelectedText",
    "ВыделятьОтрицательные": "HighlightNegative",
    "ВыравниваниеКнопок": "ButtonAlignment",
    "Высота": "Height",
    "ВысотаПодвала": "FooterHeight",
    "ВысотаСпискаВыбора": "ChoiceListHeight",
    "ВысотаШапки": "HeaderHeight",
    "Гиперссылка": "Hyperlink",
    "ГоризонтальнаяПолосаПрокрутки": "HorizontalScrollBar",
    "ГоризонтальноеПоложение": "HorizontalAlign",
    "ГоризонтальныеЛинии": "HorizontalLines",
    "Градиент": "Gradient",
    "Документ": "Document",
    "Доступность": "Enabled",
    "ЕдиницаПериодическогоВарианта": "PeriodicVariantUnit",
    "Заголовок": "Title",
    "ИзменятьНастройкуКолонок": "AllowColumnSetup",
    "ИзменятьПозициюКолонок": "AllowChangeColumnOrder",
    "ИзменятьСоставСтрок": "AllowChangeRows",
    "ИспользоватьКонтекстноеМеню": "AutoContextMenu",
    "ИсточникДанных": "SourceData",
    "Картинка": "Picture",
    "КартинкаКнопкиВыбора": "ChoiceButtonPicture",
    "КнопкаВыбора": "ChoiceButton",
    "КнопкаОткрытия": "OpenButton",
    "КнопкаОчистки": "ClearButton",
    "КнопкаРегулирования": "RegulationButton",
    "КнопкаСпискаВыбора": "ChoiceListButton",
    "Кнопки": "Buttons",
    "КоличествоСерий": "SeriesCount",
    "КоличествоТочек": "PointsCount",
    "Колонки": "Columns",
    "КонецПериодаОтображения": "PeriodEnd",
    "КонечныйУголИзмерительнойДиаграммы": "GaugeEndAngle",
    "КратностьПериодическогоВарианта": "PeriodicVariantMultiplicity",
    "МаксимальнаяВысота": "MaxHeight",
    "МаксимальнаяШирина": "MaxWidth",
    "МаксимальноеЗначение": "MaximumValue",
    "МаксимумСерий": "MaxSeries",
    "МаксимумСерийКоличество": "MaxSeriesCount",
    "МаксимумСерийПроцент": "MaxSeriesPercent",
    "Маска": "Mask",
    "Масштаб": "Scale",
    "Масштабировать": "ScalePicture",
    "МинимальноеЗначение": "MinimumValue",
    "МногострочныйРежим": "MultiLine",
    "НачалоПериодаОтображения": "PeriodStart",
    "НачальноеОтображениеДерева": "InitialTreeView",
    "НачальноеОтображениеСписка": "InitialListView",
    "НачальныйУголИзмерительнойДиаграммы": "GaugeStartAngle",
    "ОбластьЗаголовка": "TitleArea",
    "ОбластьЛегенды": "LegendArea",
    "ОбластьПостроения": "PlotArea",
    "Обновление": "Refresh",
    "ОграничениеТипа": "TypeRestriction",
    "Окантовка": "Outline",
    "Ориентация": "Orientation",
    "ОтметкаНезаполненного": "IncompleteMark",
    "ОтображаемаяОбласть": "DisplayedArea",
    "ОтображатьВыделение": "ShowSelection",
    "ОтображатьЗаголовок": "ShowTitle",
    "ОтображатьКартинку": "ShowPicture",
    "ОтображатьЛегенду": "ShowLegend",
    "ОтображатьПометку": "ShowMark",
    "ОтображатьПроценты": "ShowPercent",
    "ОтображатьТекущуюДату": "ShowCurrentDate",
    "ОтображениеЗакладок": "PagesRepresentation",
    "ОтображениеЗначенияИзмерительнойДиаграммы": "GaugeValueDisplay",
    "ОтображениеРазметки": "DisplayStyle",
    "ПалитраЦветов": "ColorPalette",
    "ПервыйВГруппе": "FirstInGroup",
    "ПеремещениеПоКалендарю": "CalendarNavigation",
    "Подвал": "Footer",
    "ПоддержкаМасштаба": "ScaleSupport",
    "ПодписиШкалыЗначенийИзмерительнойДиаграммыВдольШкалы": "GaugeScaleLabelsAlongScale",
    "Подсказка": "ToolTip",
    "ПоложениеЗаголовка": "TextPosition",
    "ПоложениеКартинки": "PicturePosition",
    "ПоложениеКартинкиНадписи": "PicturePosition",
    "ПоложениеКартинкиПанели": "PanelPicturePosition",
    "ПоложениеПодписей": "LabelsPosition",
    "ПоложениеПодписейШкалыЗначенийИзмерительнойДиаграммы": "GaugeScaleLabelsPosition",
    "ПолосыИзмерительнойДиаграммы": "GaugeBands",
    "Поля": "Fields",
    "ПорядокОбхода": "TraversalOrder",
    "ПрозрачныйФон": "TransparentBackColor",
    "ПрозрачныйФонПодписей": "TransparentLabelsBackColor",
    "ПропускатьБазовоеЗначение": "SkipBaseValue",
    "РазделительПодписей": "LabelsSeparator",
    "РазмерКартинки": "PictureSize",
    "РазрешитьНачалоПеретаскивания": "AllowDragStart",
    "РазрешитьПеретаскивание": "AllowDrag",
    "Рамка": "Border",
    "РамкаПодписей": "LabelsBorder",
    "РаспределятьПоСтраницам": "DistributeByPages",
    "РастягиватьПоВертикали": "VerticalStretch",
    "РастягиватьПоГоризонтали": "HorizontalStretch",
    "РасширенноеРедактирование": "ExtendedEdit",
    "Редактирование": "Editing",
    "РедактированиеТекста": "TextEditing",
    "РежимВводаСтрок": "InputRowsMode",
    "РежимВыбора": "SelectionMode",
    "РежимВыбораИзСписка": "ChoiceListMode",
    "РежимВыбораНезаполненного": "IncompleteChoiceMode",
    "РежимВыделения": "SelectionMode",
    "РежимВыделенияСтроки": "RowSelectionMode",
    "РежимМеню": "MenuMode",
    "РежимПароля": "PasswordMode",
    "РежимПробелов": "SpaceMode",
    "РежимПрокручиваемыхСтраниц": "ScrollablePagesMode",
    "Свет": "Light",
    "СводнаяСерия": "PivotSeries",
    "Серии": "Series",
    "СерииВСтроках": "SeriesInRows",
    "Состояние": "State",
    "СочетаниеКлавиш": "Shortcut",
    "СписокВыбора": "ChoiceList",
    "СтильОтображения": "DisplayStyle",
    "Страницы": "Pages",
    "ТекстНевыбраннойКартинки": "UnselectedPictureText",
    "ТекущаяДата": "CurrentDate",
    "ТекущаяКолонка": "CurrentColumn",
    "ТекущаяСтраница": "CurrentPage",
    "ТекущаяСтрока": "CurrentRow",
    "ТекущиеДанные": "CurrentData",
    "ТекущийРодитель": "CurrentParent",
    "ТекущийЭлемент": "CurrentItem",
    "ТипДиаграммы": "ChartKind",
    "ТипСводнойДиаграммы": "PivotChartKind",
    "ТолщинаВтулкиИзмерительнойДиаграммы": "GaugeHubThickness",
    "ТолщинаШкалыИзмерительнойДиаграммы": "GaugeScaleThickness",
    "ТолькоПросмотр": "ReadOnly",
    "Точки": "Points",
    "ТриСостояния": "ThreeState",
    "ФиксацияСлева": "LeftFixedColumns",
    "ФиксацияСправа": "RightFixedColumns",
    "Формат": "Format",
    "ФорматЗначенийВПодписях": "LabelValueFormat",
    "ФорматПроцентовВПодписях": "LabelPercentFormat",
    "ЦветВтулкиИзмерительнойДиаграммы": "GaugeHubColor",
    "ЦветВыходныхДней": "WeekendTextColor",
    "ЦветРамки": "BorderColor",
    "ЦветРамкиПодписей": "LabelsBorderColor",
    "ЦветТекста": "TextColor",
    "ЦветТекстаВыделения": "SelectionTextColor",
    "ЦветТекстаКнопки": "ButtonTextColor",
    "ЦветТекстаПодвала": "FooterTextColor",
    "ЦветТекстаПодписей": "LabelsTextColor",
    "ЦветТекстаПоля": "FieldTextColor",
    "ЦветТекстаШапки": "HeaderTextColor",
    "ЦветФона": "BackColor",
    "ЦветФонаВыделения": "SelectionBackColor",
    "ЦветФонаКнопки": "ButtonBackColor",
    "ЦветФонаПодвала": "FooterBackColor",
    "ЦветФонаПодписей": "LabelsBackColor",
    "ЦветФонаПоля": "FieldBackColor",
    "ЦветФонаЧередованияСтрок": "AlternatingRowBackColor",
    "ЦветФонаШапки": "HeaderBackColor",
    "ЧередованиеЦветовСтрок": "AlternateRowColors",
    "Шаг": "Step",
    "ШагРазметки": "MarkStep",
    "Шапка": "Header",
    "Ширина": "Width",
    "ШиринаСпискаВыбора": "ChoiceListWidth",
    "Шрифт": "Font",
    "ШрифтПодвала": "FooterFont",
    "ШрифтПодписей": "LabelsFont",
    "ШрифтШапки": "HeaderFont",
    "ЭлементСвязиПоТипу": "TypeLinkElement",
}


CONTROL_PLATFORM_PROPERTY_XML_NAME: dict[tuple[str, str], str] = {
    ("InputField", "МаксимальноеЗначение"): "MaxValue",
    ("InputField", "МинимальноеЗначение"): "MinValue",
    ("ProgressBar", "МаксимальноеЗначение"): "MaximumValue",
    ("ProgressBar", "МинимальноеЗначение"): "MinimumValue",
    ("TrackBar", "МаксимальноеЗначение"): "MaximumValue",
    ("TrackBar", "МинимальноеЗначение"): "MinimumValue",
    ("ChoiceField", "РежимВыбора"): "ChoiceMode",
    ("Table", "РежимВыбора"): "SelectionMode",
}


def platform_property_xml_name(control: str, platform_name: str) -> str:
    """Return the public XML property name for a platform palette property."""

    return CONTROL_PLATFORM_PROPERTY_XML_NAME.get(
        (control, platform_name),
        PLATFORM_PROPERTY_XML_NAME.get(platform_name, ""),
    )


def platform_event_xml_name(_control: str, platform_name: str) -> str:
    """Platform event names are the public XML event names for ordinary forms."""

    return platform_name
